#  ____  _   _ ____      ____   _____   ___            _        
# |  _ \| | | |  _ \    | ___| |___ /  / / |_ __ _ ___| | _____ 
# | |_) | |_| | |_) |___|___ \   |_ \ / /| __/ _` / __| |/ / __|
# |  __/|  _  |  __/_____|__) | ___) / / | || (_| \__ \   <\__ \
# |_|   |_| |_|_|       |____(_)____/_/   \__\__,_|___/_|\_\___/
#                                                               
# install-pkg
- name: install-pkg | Install dependencies for PHP {{ php.version }}
  when: ansible_os_family == "RedHat"
  yum:  name={{ item }} state=present
  ignore_errors: False
  with_items: php.packages.redhat.install

- name: install-pkg | Download GD {{ php.depends.libgd.version }}
  get_url: >
    url=http://ring.u-toyama.ac.jp/archives/graphics/gd/oldreleases/gd-{{ php.depends.libgd.version }}.tar.gz
    dest={{ buildroot }}

- name: install-pkg | Extract GD {{ php.depends.libgd.version }}
  unarchive: >
    src={{ buildroot }}/gd-{{ php.depends.libgd.version }}.tar.gz
    dest={{ buildroot }}
    copy=no

- name: install-pkg | configure GD {{ php.depends.libgd.version }}
  command: >
    chdir={{ buildroot }}/gd-{{ php.depends.libgd.version }}
    creates=Makefile
    /bin/sh configure 
    --prefix={{ php.depends.libgd.install }} 
    --with-png=/usr
    --with-freetype=/usr
    --with-fontconfig=/usr
    --with-jpeg=/usr
    --with-xpm=/usr

- name: install-pkg | make GD {{ php.depends.libgd.version }}
  register: make_gd_binary
  command: >
    chdir={{ buildroot }}/gd-{{ php.depends.libgd.version }} 
    creates=gd.o
    make 

- name: install-pkg | make install GD {{ php.depends.libgd.version }}
  when: make_gd_binary.changed
  command: >
    make install 
    chdir={{ buildroot }}/gd-{{ php.depends.libgd.version }}

- name: install-pkg | Symbolic links in {{ php.depends.libgd.install }}/lib64 should be created
  when: ansible_userspace_bits == "64"
  file: >
    src={{ php.depends.libgd.install }}/lib/{{ item }} 
    dest={{ php.depends.libgd.install }}/lib64/{{ item }}
    state=link
  with_items: [ libgd.a, libgd.la, libgd.so, libgd.so.2, libgd.so.2.0.0 ]

