#  __  __       ____   ___  _         ____   ____    ___            _        
# |  \/  |_   _/ ___| / _ \| |       | ___| | ___|  / / |_ __ _ ___| | _____ 
# | |\/| | | | \___ \| | | | |   ____|___ \ |___ \ / /| __/ _` / __| |/ / __|
# | |  | | |_| |___) | |_| | |__|_____|__) | ___) / / | || (_| \__ \   <\__ \
# |_|  |_|\__, |____/ \__\_\_____|   |____(_)____/_/   \__\__,_|___/_|\_\___/
#         |___/                                                              
# make-config
- name: make-config | Each directory should be created in {{ mysql.serverroot }}
  file: >
    path={{ mysql.serverroot }}/{{ item }} 
    mode=0755
    owner={{ mysql.user.username }} 
    group={{ mysql.user.group }}
    state=directory 
  with_items:
    - etc
    - data
    - dump
    - var/run
    - var/log

- name: make-config | {{ mysql.serverroot }} should be owned by {{ mysql.user.username }}
  file: >
    path={{ mysql.serverroot }}
    owner={{ mysql.user.username }}
    group={{ mysql.user.group }}
    state=directory

- name: make-config | Calculation(innodb_buffer_pool_size)
  register: innodb_buffer_pool_size
  changed_when: innodb_buffer_pool_size.rc > 0
  command: >
    perl -le 'print int {{ ansible_memtotal_mb }} * 0.60'

- name: make-config | Calculation(innodb_log_file_size)
  register: innodb_log_file_size
  changed_when: innodb_log_file_size.rc > 0
  command: >
    perl -le 'print int {{ innodb_buffer_pool_size.stdout }} * 0.20'

- name: make-config | Calculation(thread_concurrency)
  register: thread_concurrency
  changed_when: thread_concurrency.rc > 0
  command: >
    perl -le 'print int {{ ansible_processor_vcpus }} * 2'

- name: make-config | Deploy {{ mysql.conf.file }} into {{ mysql.serverroot }}/etc/my.cnf
  template: >
    src=opt/mysql/etc/{{ mysql.conf.file }}.j2
    dest={{ mysql.serverroot }}/etc/my.cnf
    backup=yes

- name: make-config | Symbolic link to mysql related command should be created
  file: >
    src={{ mysql.serverroot }}/bin/{{ item }}
    dest=/usr/local/bin/{{ item }}
    state=link
  with_items:
    - mysql
    - mysql_config
    - mysqladmin

- name: make-config | Install MySQLdb Python package
  pip:  name=mysql-python state=present

- name: make-config | Deploy /etc/logrotate.d/{{ mysql.rotatefile }}
  when: ansible_os_family in [ 'RedHat', 'Debian' ]
  template: >
    src=etc/logrotate.d/mysql-log-rotate.j2
    dest=/etc/logrotate.d/{{ mysql.rotatefile }}
    backup=yes

- name: make-config | MySQL database should be installed
  register: install_mysql_database
  command: >
    chdir={{ mysql.datadirectory }}
    creates=mysql/db.MYI
    {{ mysql.serverroot }}/scripts/mysql_install_db 
    --user={{ mysql.user.username }}
    --basedir={{ mysql.serverroot }} 
    --datadir={{ mysql.datadirectory }}

- name: make-config | Deploy /root/.my.cnf
  register: root_my_cnf
  template: >
    src=root/dot-my.cnf.j2
    dest=/root/.my.cnf

- name: make-config | Change mode /root/.my.cnf
  when: root_my_cnf|changed
  file: >
    path=/root/.my.cnf
    mode=0600
    owner=root
    state=file

