#      _                          _      ___            _        
#   __| | _____   _____  ___ ___ | |_   / / |_ __ _ ___| | _____ 
#  / _` |/ _ \ \ / / _ \/ __/ _ \| __| / /| __/ _` / __| |/ / __|
# | (_| | (_) \ V /  __/ (_| (_) | |_ / / | || (_| \__ \   <\__ \
#  \__,_|\___/ \_/ \___|\___\___/ \__/_/   \__\__,_|___/_|\_\___/
#                                                                
# get-archive
- name: get-archive | Download dovecot {{ dovecot.version }} at {{ buildroot }}
  get_url: >
    url=http://dovecot.org/releases/{{ dovecot.majorver }}/dovecot-{{ dovecot.version }}.tar.gz
    dest={{ buildroot }}/dovecot-{{ dovecot.version }}.tar.gz

- name: get-archive | Extract {{ buildroot }}/dovecot-{{ dovecot.version }}
  unarchive: >
    src={{ buildroot }}/dovecot-{{ dovecot.version }}.tar.gz
    dest={{ buildroot }}
    creates={{ buildroot }}/dovecot-{{ dovecot.version }}
    copy=no

