#      _                          _      ___            _        
#   __| | _____   _____  ___ ___ | |_   / / |_ __ _ ___| | _____ 
#  / _` |/ _ \ \ / / _ \/ __/ _ \| __| / /| __/ _` / __| |/ / __|
# | (_| | (_) \ V /  __/ (_| (_) | |_ / / | || (_| \__ \   <\__ \
#  \__,_|\___/ \_/ \___|\___\___/ \__/_/   \__\__,_|___/_|\_\___/
#                                                                
- include: install-pkg.yml
  when: dovecot.updateonly == False
- include: create-user.yml
  when: dovecot.updateonly == False
- include: get-archive.yml
- include: compile-src.yml
- include: make-config.yml
  when: dovecot.updateonly == False
- include: boot-script.yml

