#  ____                 _                 _ _    __                    
# / ___|  ___ _ __   __| |_ __ ___   __ _(_) |  / /_   ____ _ _ __ ___ 
# \___ \ / _ \ '_ \ / _` | '_ ` _ \ / _` | | | / /\ \ / / _` | '__/ __|
#  ___) |  __/ | | | (_| | | | | | | (_| | | |/ /  \ V / (_| | |  \__ \
# |____/ \___|_| |_|\__,_|_| |_| |_|\__,_|_|_/_/    \_/ \__,_|_|  |___/
#                                                                      
sendmail:
  started: False
  rebuild: False
  version: 8.15.1
  udpateonly: False
  serverroot: /opt/sendmail
  workingdir: /usr/local/src
  initscript: sendmail
  mtaqueue: /var/spool/queues
  msaqueue: /var/spool/cqueue
  user:
    mta:
      username: sendmail
      uid: 625
      gid: 625
      home: /var/spool/queues
      group: sendmail
      shell: /sbin/nolgin
      comment: Sendmail
    msa:
      username: smsubmit
      uid: 587
      gid: 587
      home: /var/spool/cqueue
      group: smsubmit
      shell: /sbin/nologin
      comment: "'Sendmail Submission'"
    mda:
      username: virtmail
      uid: 660
      gid: 660
      home: /home/virtmail
      group: virtmail
      shell: /bin/sh
      comment: "'Virtual Mailbox'"
procmail:
  rebuild: False
  version: 3.22
  install: /opt/sendmail
  spool: /var/spool/procmail

maildrop:
  rebuild: False
  version: 2.7.2
  install: /opt/sendmail

