#     _                     _             ___            _        
#    / \   _ __   __ _  ___| |__   ___   / / |_ __ _ ___| | _____ 
#   / _ \ | '_ \ / _` |/ __| '_ \ / _ \ / /| __/ _` / __| |/ / __|
#  / ___ \| |_) | (_| | (__| | | |  __// / | || (_| \__ \   <\__ \
# /_/   \_\ .__/ \__,_|\___|_| |_|\___/_/   \__\__,_|___/_|\_\___/
#         |_|                                                     
# boot-script
- name: boot-script | RedHat | Deploy /etc/init.d/{{ apache.initscript }}
  when: ansible_os_family == "RedHat"
  template: >
    src=etc/init.d/httpd.RedHat.j2
    dest=/etc/init.d/{{ apache.initscript }}
    mode=0755
    owner=root
    group=root

- name: boot-script | RedHat | Install init script /etc/rc.d/init.d/{{ apache.initscript }}
  notify: Start Apache
  when: ansible_os_family == "RedHat"
  shell: >
    /sbin/chkconfig --add {{ apache.initscript }}
    creates=/etc/rc.d/rc0.d/K15{{ apache.initscript }}

- name: boot-script | Turn on init script /etc/rc.d/init.d/{{ apache.initscript }}
  service: name={{ apache.initscript }} enabled=yes

