#  _     _           _  ___    ___            _        
# | |__ (_)_ __   __| |/ _ \  / / |_ __ _ ___| | _____ 
# | '_ \| | '_ \ / _` | (_) |/ /| __/ _` / __| |/ / __|
# | |_) | | | | | (_| |\__, / / | || (_| \__ \   <\__ \
# |_.__/|_|_| |_|\__,_|  /_/_/   \__\__,_|___/_|\_\___/
#                                                      
# make-config
- name: make-config | chroot directory for bind9 should be created
  file: >
    path={{ bind.changeroot }}
    mode=0755
    state=directory
    owner={{ bind.user.username }}
    group={{ bind.user.group }}

- name: make-config | Each directory for bind9 should be created
  file: >
    path={{ bind.changeroot }}/{{ item }}
    mode=0755
    state=directory
    owner={{ bind.user.username }}
    group={{ bind.user.group }}
  with_items:
    - dev
    - etc
    - var/run
    - var/log
    - var/data/masters/l
    - var/data/masters/1
    - var/data/slaves
    - tmp

- name: mame-config | /dev/random
  shell: >
    chdir={{ bind.changeroot }}/dev
    creates={{ item.name }}
    mknod -m 666 {{ item.name }} c 1 {{ item.minor }}
  with_items:
    - { name: 'random', minor: 8 }
    - { name: 'urandom', minor: 9 }
    - { name: 'zero', minor: 5 }
    - { name: 'null', minor: 3 }

- name: make-config | Sub directories for master zone should be created
  file: >
    path={{ bind.changeroot }}/var/data/masters/{{ item }}
    mode=0755
    owner={{ bind.user.username }}
    group={{ bind.user.group }}
    state=directory
  with_items: bind.zone.subdirs

- name: make-config | Sub directories for slave zone should be created
  file: >
    path={{ bind.changeroot }}/var/data/slaves/{{ item }}
    mode=0755
    owner={{ bind.user.username }}
    group={{ bind.user.group }}
    state=directory
  with_items: bind.zone.subdirs

- name: make-config | Deploy {{ bind.changeroot }}/etc/named.conf
  notify: Restart BIND
  template: >
    src=opt/named/etc/named.conf.j2
    dest={{ bind.changeroot }}/etc/named.conf

- name: make-config | localtime file must exist
  shell: >
    chdir={{ bind.changeroot }}
    creates={{ bind.changeroot }}/etc/localtime
    /bin/cp /etc/localtime {{ bind.changeroot }}/etc/localtime

- name: make-config | {{ bind.changeroot }}/etc/rndc.key should be created
  shell: >
    chdir={{ bind.changeroot }}
    creates={{ bind.changeroot }}/etc/{{ ansible_hostname }}-rndc-key
    {{ bind.serverroot }}/sbin/rndc-confgen -a -p 953
    -c /etc/{{ ansible_hostname }}-rndc-key 
    -k {{ ansible_hostname }}-rndc-key
    -r /dev/urandom
    -u {{ bind.user.username }}
    -t {{ bind.changeroot }}

- name: make-config | {{ bind.changeroot }}/etc/rndc.key should be linked
  file: >
    src={{ bind.changeroot }}/etc/{{ ansible_hostname }}-rndc-key
    path={{ bind.changeroot }}/etc/rndc.key
    state=link

- name: make-config | {{ bind.changeroot }}/etc/rootzone-dnssec-keys should be deployed
  shell: >
    chdir={{ bind.workingdir }}/bind-{{ bind.version }}
    creates={{ bind.changeroot }}/etc/rootzone-dnssec-keys
    /bin/cp bind.keys {{ bind.changeroot }}/etc/rootzone-dnssec-keys

- name: make-config | {{ bind.changeroot }}/var/data/named.root should be deployed
  get_url: >
    url=ftp://rs.internic.net/domain/named.root
    dest={{ bind.changeroot }}/var/data/named.root

- name: make-config | localhost.zone and 127.in-addr.arpa.rev should be deployed
  copy: >
    src=opt/named/var/data/masters/{{ item }}
    dest={{ bind.changeroot }}/var/data/masters/{{ item }}
  with_items:
    - l/localhost.zone
    - 1/127.in-addr.arpa.rev

- name: make-config | localhost.zone and 127.in-addr.arpa.rev should be owned by {{ bind.user.username }}
  file: >
    path={{ bind.changeroot }}/var/data/masters/{{ item }}
    owner={{ bind.user.username }}
    group={{ bind.user.group }}
    mode=0644
  with_items:
    - l/localhost.zone
    - 1/127.in-addr.arpa.rev

- name: make-config | dig command should be linked to /usr/local/bin/dig
  file: >
    src={{ bind.serverroot }}/bin/dig
    dest=/usr/local/bin/dig
    state=link

