#   __ _                        _ _    __                    
#  / _(_)_ __ _____      ____ _| | |  / /_   ____ _ _ __ ___ 
# | |_| | '__/ _ \ \ /\ / / _` | | | / /\ \ / / _` | '__/ __|
# |  _| | | |  __/\ V  V / (_| | | |/ /  \ V / (_| | |  \__ \
# |_| |_|_|  \___| \_/\_/ \__,_|_|_/_/    \_/ \__,_|_|  |___/
#                                                            
firewall:
 started: True
 program: iptables
 workingdir: /usr/local/src
 port:
  ssh: 22

