#  ____                 _                 _ _    ___            _        
# / ___|  ___ _ __   __| |_ __ ___   __ _(_) |  / / |_ __ _ ___| | _____ 
# \___ \ / _ \ '_ \ / _` | '_ ` _ \ / _` | | | / /| __/ _` / __| |/ / __|
#  ___) |  __/ | | | (_| | | | | | | (_| | | |/ / | || (_| \__ \   <\__ \
# |____/ \___|_| |_|\__,_|_| |_| |_|\__,_|_|_/_/   \__\__,_|___/_|\_\___/
#                                                                        
# get-archive
- name: get-archive | Download procmail {{ procmail.version }} at {{ buildroot }}
  ignore_errors: True
  chagend_when: get_procmail.rc == 0
  register: get_procmail
  get_url: >
    url=ftp://ftp.ring.gr.jp/pub/net/mail/procmail/procmail-{{ procmail.version }}.tar.gz
    dest={{ buildroot }}/procmail-{{ procmail.version }}.tar.gz

- name: get-archive | Deploy procmail-{{ procmail.verison }}.tar.gz
  when: get_procmail|failed
  copy: >
    src=procmail-{{ procmail.version }}.tar.gz
    dest={{ buildroot }}

- name: get-archive | Extract {{ buildroot }}/procmail-{{ procmail.version }}.tar.gz
  unarchive: >
    src={{ buildroot }}/procmail-{{ procmail.version }}.tar.gz
    dest={{ buildroot }}
    creates={{ buildroot }}/procmail-{{ procmail.version }}
    copy=no

- name: get-archive | Download maildrop {{ maildrop.version }} at {{ buildroot }}
  ignore_errors: True
  changed_when: get_maildrop.rc == 0
  register: get_maildrop
  get_url: >
    url=ftp://ftp.jaist.ac.jp/pub/sourceforge/c/co/courier/maildrop/{{ maildrop.version }}/maildrop-{{ maildrop.version }}.tar.bz2
    dest={{ buildroot }}/maildrop-{{ maildrop.version }}.tar.bz2

- name: get-archive | Deploy maildrop-{{ maildrop.verison }}.tar.bz2
  when: get_maildrop|failed
  copy: >
    src=maildrop-{{ maildrop.version }}.tar.bz2
    dest={{ buildroot }}

- name: get-archive | Extract {{ buildroot }}/maildrop-{{ maildrop.version }}.tar.bz2
  unarchive: >
    src={{ buildroot }}/maildrop-{{ maildrop.version }}.tar.bz2
    dest={{ buildroot }}
    creates={{ buildroot }}/maildrop-{{ maildrop.version }}
    copy=no

- name: get-archive | Download sendmail {{ sendmail.version }} at {{ buildroot }}
  get_url: >
    url=ftp://ftp.sendmail.org/pub/sendmail/sendmail.{{ sendmail.version }}.tar.gz
    dest={{ buildroot }}/sendmail.{{ sendmail.version }}.tar.gz

- name: get-archive | Extract {{ buildroot }}/sendmail-{{ sendmail.version }}
  unarchive: >
    src={{ buildroot }}/sendmail.{{ sendmail.version }}.tar.gz
    dest={{ buildroot }}
    creates={{ buildroot }}/sendmail-{{ sendmail.version }}
    copy=no

