#     _                     _             ___            _        
#    / \   _ __   __ _  ___| |__   ___   / / |_ __ _ ___| | _____ 
#   / _ \ | '_ \ / _` |/ __| '_ \ / _ \ / /| __/ _` / __| |/ / __|
#  / ___ \| |_) | (_| | (__| | | |  __// / | || (_| \__ \   <\__ \
# /_/   \_\ .__/ \__,_|\___|_| |_|\___/_/   \__\__,_|___/_|\_\___/
#         |_|                                                     
# compile-src
#
- name: 'compile-src | REBUILD | make clean'
  command: >
    make clean
    chdir={{ local.src }}/httpd-{{ apache.version }}/
    removes=Makefile
  when: apache.rebuild == 1

- name: 'compile-src | {{ apache.serverroot }} directory should be created'
  file: >
    path={{ apache.serverroot }}
    mode=0755
    state=directory

- name: 'compile-src | configure apache {{ apache.version }}'
  notify: Restart Apache
  command: >
    chdir={{ local.src }}/httpd-{{ apache.version }}/
    /bin/sh configure
    --prefix={{ apache.serverroot }}
    --enable-vhost-alias
    --enable-rewrite
    --enable-so
    --enable-logio
    --disable-include
    --disable-filter
    --disable-charset-lite
    --disable-autoindex
    --disable-cgi
    --disable-cgid
    --disable-userdir
    creates=Makefile

- name: 'compile-src | make apache {{ apache.version }}'
  notify: Restart Apache
  command: >
    make
    chdir={{ local.src }}/httpd-{{ apache.version }}/
    creates=httpd
  register: make_apache_binary

- name: 'compile-src | make install apache {{ apache.version }}'
  when: make_apache_binary.changed
  notify: Restart Apache
  command: >
    make install
    chdir={{ local.src }}/httpd-{{ apache.version }}/

