#                                      ___            _        
#   ___ _ __   __ _ _ __ ___  _ __    / / |_ __ _ ___| | _____ 
#  / __| '_ \ / _` | '_ ` _ \| '_ \  / /| __/ _` / __| |/ / __|
# | (__| |_) | (_| | | | | | | | | |/ / | || (_| \__ \   <\__ \
#  \___| .__/ \__,_|_| |_| |_|_| |_/_/   \__\__,_|___/_|\_\___/
#      |_|                                                     
- name: 'main | Download cpanm'
  get_url: >
    url='http://xrl.us/cpanm';
    dest={{ local.src }}/cpanm

- name: 'main | Install cpanm into {{ local.dir }}/bin/cpanm'
  shell: >
    chdir={{ local.src }}
    install -o root -m 0755 cpanm {{ local.dir }}/bin
    creates={{ local.dir }}/bin/cpanm

