#   ___                   ____  __  __ _____ ____  ____    __                    
#  / _ \ _ __   ___ _ __ / ___||  \/  |_   _|  _ \|  _ \  / /_   ____ _ _ __ ___ 
# | | | | '_ \ / _ \ '_ \\___ \| |\/| | | | | |_) | | | |/ /\ \ / / _` | '__/ __|
# | |_| | |_) |  __/ | | |___) | |  | | | | |  __/| |_| / /  \ V / (_| | |  \__ \
#  \___/| .__/ \___|_| |_|____/|_|  |_| |_| |_|   |____/_/    \_/ \__,_|_|  |___/
#       |_|                                                                      
#
opensmtpd:
  started: True
  rebuild: False
  version: 5.4.5
  updateonly: False
  initscript: opensmtpd
  serverroot: /opt/opensmtpd
  workingdir: /usr/local/src
  mtaqueue: /var/spool/queues
  msaqueue: /var/spool/cqueue 
  user:
    daemon:
      username: _smtpd
      group: _smtpd
      uid: 6309
      gid: 6309
      comment: '"SMTP Daemon"'
    queue:
      username: _smtpq
      group: _smtpq
      uid: 6310
      gid: 6310
      comment: '"SMTP Queue"'
    mda:
      username: virtmail
      uid: 660
      gid: 660
      home: /home/virtmail
      group: virtmail
      shell: /bin/sh
      comment: "'Virtual Mailbox'"
maildrop:
  rebuild: False
  version: 2.7.1
  install: /opt/opensmtpd
