#                                               ___            _        
#   ___ ___  _ __ ___  _ __ ___   ___  _ __    / / |_ __ _ ___| | _____ 
#  / __/ _ \| '_ ` _ \| '_ ` _ \ / _ \| '_ \  / /| __/ _` / __| |/ / __|
# | (_| (_) | | | | | | | | | | | (_) | | | |/ / | || (_| \__ \   <\__ \
#  \___\___/|_| |_| |_|_| |_| |_|\___/|_| |_/_/   \__\__,_|___/_|\_\___/
#                  _                               __ _       
#  _ __ ___   __ _| | _____        ___ ___  _ __  / _(_) __ _ 
# | '_ ` _ \ / _` | |/ / _ \_____ / __/ _ \| '_ \| |_| |/ _` |
# | | | | | | (_| |   <  __/_____| (_| (_) | | | |  _| | (_| |
# |_| |_| |_|\__,_|_|\_\___|      \___\___/|_| |_|_| |_|\__, |
#                                                       |___/ 
- name: 'Be sure {{ local.src }} directory should be exist'
  file: >
    path={{ local.src }}
    mode=0775
    owner=root
    group=wheel
    state=directory

