#   __ _                        _ _    ___            _        
#  / _(_)_ __ _____      ____ _| | |  / / |_ __ _ ___| | _____ 
# | |_| | '__/ _ \ \ /\ / / _` | | | / /| __/ _` / __| |/ / __|
# |  _| | | |  __/\ V  V / (_| | | |/ / | || (_| \__ \   <\__ \
# |_| |_|_|  \___| \_/\_/ \__,_|_|_/_/   \__\__,_|___/_|\_\___/
#                                                              
# make-config
- name: make-config | Deploy each file in /etc/firewall(1)
  register: firewall_scripts1
  template: >
    src=etc/firewall/{{ item }}.j2
    dest=/etc/firewall/{{ item }}
    backup=yes
  with_items:
    - my-ipv4-address
    - firewall-rules
    - trusted-hosts
    - extroot-hosts
    - monitor-hosts

- name: make-config | Deploy each file in /etc/firewall(2)
  when: ansible_eth1 is defined
  register: firewall_scripts2
  template: >
    src=etc/firewall/{{ item }}.j2
    dest=/etc/firewall/{{ item }}
    backup=yes
  with_items:
    - internal-hosts

- name: make-config | Be sure the wall should be deployed
  when: ansible_system == "Linux" and firewall.started
  register: wall_has_been_deployed
  changed_when: "'OK' in wall_has_been_deployed"
  shell: >
    chdir=/etc/firewall
    ./make-linux-iptables wall

- name: make-config | Be sure /etc/sysconfig/iptables should be created
  when: ansible_system == "Linux" and firewall.started
  shell: >
    chdir=/etc/firewall
    creates=/etc/sysconfig/{{ firewall.program }}
    ./make-linux-iptables dump > /etc/sysconfig/{{ firewall.program }}

- name: make-config | Be sure /etc/sysconfig/iptables should be updated
  when: ansible_system == "Linux" and firewall.started
  when: firewall_scripts1.changed or firewall_scripts2.changed
  shell: >
    chdir=/etc/firewall
    ./make-linux-iptables dump > /etc/sysconfig/{{ firewall.program }}

