#  ____                 _                 _ _    ___            _        
# / ___|  ___ _ __   __| |_ __ ___   __ _(_) |  / / |_ __ _ ___| | _____ 
# \___ \ / _ \ '_ \ / _` | '_ ` _ \ / _` | | | / /| __/ _` / __| |/ / __|
#  ___) |  __/ | | | (_| | | | | | | (_| | | |/ / | || (_| \__ \   <\__ \
# |____/ \___|_| |_|\__,_|_| |_| |_|\__,_|_|_/_/   \__\__,_|___/_|\_\___/
#                                                                        
# make-config
#  ____ ____ ____ ____ ____ ____ ____ ____ 
# ||v |||i |||r |||t |||m |||a |||i |||l ||
# ||__|||__|||__|||__|||__|||__|||__|||__||
# |/__\|/__\|/__\|/__\|/__\|/__\|/__\|/__\|
#
- name: make-config | virtmail | Each directory should be created
  file: >
    path={{ procmail.install }}/{{ item }}
    mode=0755
    owner=root
    state=directory
  with_items:
    - etc
    - etc/rcs

#  ____ ____ ____ ____ ____ ____ ____ ____ 
# ||p |||r |||o |||c |||m |||a |||i |||l ||
# ||__|||__|||__|||__|||__|||__|||__|||__||
# |/__\|/__\|/__\|/__\|/__\|/__\|/__\|/__\|
#
- name: make-config | procmail | Log file should be created
  file: >
    path=/var/log/procmail-local.log
    mode=0600
    owner=root
    state=touch

- name: make-config | procmail spool directory should have been created
  file: >
    path={{ procmail.spool }}
    mode=0770
    owner=root
    group={{ sendmail.user.mta.group }}
    state=directory

#  ____ ____ ____ ____ ____ ____ ____ ____ 
# ||m |||a |||i |||l |||d |||r |||o |||p ||
# ||__|||__|||__|||__|||__|||__|||__|||__||
# |/__\|/__\|/__\|/__\|/__\|/__\|/__\|/__\|
#
- name: make-config | maildrop | Log file should be created
  file: >
    path=/var/log/maildrop-virtual.log
    mode=0600
    owner={{ sendmail.user.mda.username }}
    state=touch

- name: make-config | /root/Maildir directories should have been created
  file: >
    path=/root/Maildir/{{ item }}
    mode=0700
    state=directory
  with_items: [ "cur", "new", "tmp" ]

- name: make-config | /etc/skel/Maildir directories should have been created
  file: >
    path=/etc/skel/Maildir/{{ item }}
    mode=0700
    state=directory
  with_items: [ "cur", "new", "tmp" ]

#  ____ ____ ____ ____ ____ ____ ____ ____ 
# ||s |||e |||n |||d |||m |||a |||i |||l ||
# ||__|||__|||__|||__|||__|||__|||__|||__||
# |/__\|/__\|/__\|/__\|/__\|/__\|/__\|/__\|
#
- name: make-config | MTA Queue directories should have been created
  file: >
    path={{ sendmail.mtaqueue }}/q.{{ item }}
    mode=0700
    owner=root
    group={{ sendmail.user.mta.group }}
    state=directory
  with_items: [ 0, 1, 2, 3 ]

- name: make-config | MSP Queue directories should have been created
  file: >
    path={{ sendmail.msaqueue }}
    mode=0770
    owner={{ sendmail.user.msa.username }}
    group={{ sendmail.user.msa.group }}
    state=directory

- name: make-config | /var/spool/hoststat should be created
  file: >
    path=/var/spool/hoststat
    state=directory

- name: make-config | /usr/sbin/smtpd should be created
  file: >
    src=/usr/sbin/sendmail
    path=/usr/sbin/smtpd
    state=link

- name: make-config | /var/adm/sm.bin should be created
  file: >
    path=/var/adm/sm.bin
    mode=0751
    owner=root
    state=directory

- name: make-config | alias file should be created
  template: >
    src=etc/mail/aliases.j2
    dest={{ sendmail.configroot }}/aliases

- name: make-config | Copy cf directory
  shell: >
    chdir={{ sendmail.workingdir }}/sendmail-{{ sendmail.version }}/
    /bin/cp -Rp ./cf {{ sendmail.configroot }}/
    creates={{ sendmail.configroot }}/cf

- name: make-config | Deploy submit.mc file
  template: >
    src=etc/mail/submit.mc.j2
    dest={{ sendmail.configroot }}/cf/cf/submit.mc

- name: make-config | Install submit.cf
  shell: >
    chdir={{ sendmail.configroot }}/cf/cf
    {{ sendmail.workingdir }}/sendmail-{{ sendmail.version }}/devtools/bin/install.sh 
    -c -o root -g bin -m 0444 submit.cf {{ sendmail.configroot }}/submit.cf

- name: make-config | Deploy sendmail.mc file
  when: ansible_system == "Linux"
  template: >
    src=etc/mail/sendmail.mc.{{ ansible_system }}.j2
    dest={{ sendmail.configroot }}/cf/cf/sendmail.mc

- name: make-config | Deploy virtmail.m4 file
  template: >
    src=etc/mail/virtmail.m4.j2
    dest={{ sendmail.configroot }}/cf/mailer/virtmail.m4

- name: make-config | Build sendmail.cf and submit.cf
  shell: >
    chdir={{ sendmail.configroot }}/cf/cf
    make {{ item }}.cf
  with_items:
    - sendmail
    - submit

- name: make-config | Install sendmail.cf
  shell: >
    chdir={{ sendmail.configroot }}/cf/cf
    {{ sendmail.workingdir }}/sendmail-{{ sendmail.version }}/devtools/bin/install.sh 
    -c -o root -g bin -m 0444 sendmail.cf {{ sendmail.configroot }}/sendmail.cf

- name: make-config | Deploy files into {{ sendmail.configroot }}
  template: >
    src=etc/mail/{{ item }}.j2
    dest={{ sendmail.configroot }}/{{ item }}
  with_items:
      - Makefile
      - access
      - aliases
      - authinfo
      - daemon-options
      - generics-domains
      - genericstable
      - local-host-names
      - mailertable
      - masquerade-domains
      - queue-interval
      - relay-domains
      - sid-options
      - sid-pass-domains
      - sid-peer-hosts
      - trusted-users
      - virtuser-domains
      - virtusertable

- name: make-config | Deploy files into {{ procmail.install }}
  template: >
    src=etc/mail/{{ item }}.j2
    dest={{ procmail.install}}/etc/{{ item }}
  with_items:
      - maildroprc
      - procmailrc
