#  ____           _                 ____   ___  _        ___            _        
# |  _ \ ___  ___| |_ __ _ _ __ ___/ ___| / _ \| |      / / |_ __ _ ___| | _____ 
# | |_) / _ \/ __| __/ _` | '__/ _ \___ \| | | | |     / /| __/ _` / __| |/ / __|
# |  __/ (_) \__ \ || (_| | | |  __/___) | |_| | |___ / / | || (_| \__ \   <\__ \
# |_|   \___/|___/\__\__, |_|  \___|____/ \__\_\_____/_/   \__\__,_|___/_|\_\___/
#                    |___/                                                       
# make-config
- name: make-config | {{ postgresql.serverroot }} should be 0755
  file: >
    path={{ postgresql.serverroot }}
    mode=0755
    state=directory
    owner={{ postgresql.user.username }}
    group={{ postgresql.user.group }}
# 
- name: make-config | {{ postgresql.datadirectory }} should be 0700
  file: >
    path={{ postgresql.datadirectory }}
    mode=0700
    state=directory
    owner={{ postgresql.user.username }}
    group={{ postgresql.user.group }}

- name: make-config | Each directory should be created
  file: >
    path={{ postgresql.serverroot }}/{{ item }}
    mode=0755
    state=directory
    owner={{ postgresql.user.username }}
    group={{ postgresql.user.group }}
  with_items:
    - dump
    - logs

- name: make-config | Symbolic link to pgsql related command should be created
  file: >
    src={{ postgresql.serverroot }}/bin/{{ item }}
    dest=/usr/local/bin/{{ item }}
    state=link
  with_items:
    - psql
    - pg_dump
    - pg_dumpall
    - createuser
    - createdb

- name: make-config | {{ postgresql.datadirectory }} should be initialized
  shell: >
    chdir={{ postgresql.serverroot }}
    creates={{ postgresql.datadirectory }}/base
    sudo -u {{ postgresql.user.username }} 
    -s {{ postgresql.serverroot }}/bin/initdb --no-locale -EUTF-8 -D{{ postgresql.datadirectory }}

- name: make-config | Deploy configuration files into {{ postgresql.datadirectory }}
  notify: Restart PostgreSQL
  template: >
    src=data/{{ item }}.j2
    dest={{ postgresql.datadirectory }}/{{ item }}
    backup=yes
  with_items:
    - postgresql.conf
    - pg_hba.conf

