#  __  __       ____   ___  _         ____   ____    ___            _        
# |  \/  |_   _/ ___| / _ \| |       | ___| | ___|  / / |_ __ _ ___| | _____ 
# | |\/| | | | \___ \| | | | |   ____|___ \ |___ \ / /| __/ _` / __| |/ / __|
# | |  | | |_| |___) | |_| | |__|_____|__) | ___) / / | || (_| \__ \   <\__ \
# |_|  |_|\__, |____/ \__\_\_____|   |____(_)____/_/   \__\__,_|___/_|\_\___/
#         |___/                                                              
#  _                 _                      _       _   
# | |__   ___   ___ | |_      ___  ___ _ __(_)_ __ | |_ 
# | '_ \ / _ \ / _ \| __|____/ __|/ __| '__| | '_ \| __|
# | |_) | (_) | (_) | ||_____\__ \ (__| |  | | |_) | |_ 
# |_.__/ \___/ \___/ \__|    |___/\___|_|  |_| .__/ \__|
#                                            |_|        
- name: 'Deploy startup script {{ mysql.serverroot }}/bin/mysql.server'
  template: >
    src=mysql.server.j2
    dest={{ mysql.serverroot }}/bin/mysql.server
    mode=0755
    owner={{ mysql.user.username }}
    group={{ mysql.user.group }}

- name: '(RedHat) Deploy init script /etc/rc.d/init.d/mysql'
  when: ansible_os_family == "RedHat"
  template: >
    src=mysql.server.j2
    dest=/etc/rc.d/init.d/mysql
    mode=0755
    owner=root
    group=root

- name: '(RedHat) Install init script /etc/rc.d/init.d/mysql'
  when: ansible_os_family == "RedHat"
  shell: >
    /sbin/chkconfig --add mysql
    creates=/etc/rc.d/rc0.d/K36mysql

- name: 'Turn on init script'
  service: name=mysql enabled=yes

- name: 'Start MySQL for the first mysqladmin command'
  when: install_mysql_database.changed
  service: name=mysql state=started

- name: 'Set root password for MySQL by mysqladmin'
  when: install_mysql_database.changed
  shell: >
      {{ mysql.serverroot }}/bin/mysqladmin -uroot password "{{ mysql.conf.rootpasswd }}"

