#  __  __       ____   ___  _         ____   ____    ___            _        
# |  \/  |_   _/ ___| / _ \| |       | ___| | ___|  / / |_ __ _ ___| | _____ 
# | |\/| | | | \___ \| | | | |   ____|___ \ |___ \ / /| __/ _` / __| |/ / __|
# | |  | | |_| |___) | |_| | |__|_____|__) | ___) / / | || (_| \__ \   <\__ \
# |_|  |_|\__, |____/ \__\_\_____|   |____(_)____/_/   \__\__,_|___/_|\_\___/
#         |___/                                                              
# boot-script
#
- name: 'boot-script | Deploy {{ mysql.serverroot }}/bin/mysql.server'
  template: >
    src=opt/mysql/bin/mysql.server.j2
    dest={{ mysql.serverroot }}/bin/mysql.server
    mode=0755
    owner={{ mysql.user.username }}
    group={{ mysql.user.group }}

- name: 'boot-script | RedHat | Deploy /etc/init.d/mysql'
  when: ansible_os_family == "RedHat"
  template: >
    src=opt/mysql/bin/mysql.server.j2
    dest=/etc/init.d/mysql
    mode=0755
    owner=root
    group=root

- name: 'boot-script | RedHat | Install /etc/rc.d/init.d/mysql'
  when: ansible_os_family == "RedHat"
  shell: >
    /sbin/chkconfig --add mysql
    creates=/etc/rc.d/rc0.d/K36mysql

- name: 'boot-script | Turn on init script'
  service: name=mysql enabled=yes

- name: 'boot-script | Start MySQL for the first mysqladmin command'
  when: install_mysql_database.changed
  service: name=mysql state=started

- name: 'boot-script | Set root password for MySQL by mysqladmin'
  when: install_mysql_database.changed
  shell: >
      {{ mysql.serverroot }}/bin/mysqladmin -uroot password "{{ mysql.conf.rootpasswd }}"

