#  __  __       ____   ___  _         ____   ____    ___            _        
# |  \/  |_   _/ ___| / _ \| |       | ___| | ___|  / / |_ __ _ ___| | _____ 
# | |\/| | | | \___ \| | | | |   ____|___ \ |___ \ / /| __/ _` / __| |/ / __|
# | |  | | |_| |___) | |_| | |__|_____|__) | ___) / / | || (_| \__ \   <\__ \
# |_|  |_|\__, |____/ \__\_\_____|   |____(_)____/_/   \__\__,_|___/_|\_\___/
#         |___/                                                              
# compile-src
#
- name: 'compile-src | REBUILD | Remove CMakeCache.txt'
  command: >
    chdir={{ local.src }}/mysql-{{ mysql.version }}/
    removes=CMakeCache.txt
    rm CMakeCache.txt
  when: mysql.rebuild == 1

- name: 'compile-src | REBUILD | make clean'
  command: >
    chdir={{ local.src }}/mysql-{{ mysql.version }}/
    make clean
    removes=CMakeCache.txt
  when: mysql.rebuild == 1

- name: 'compile-src | cmake MySQL {{ mysql.version }}'
  notify: Restart MySQL
  command: >
    chdir={{ local.src }}/mysql-{{ mysql.version }}
    cmake . 
      -DCMAKE_INSTALL_PREFIX={{ mysql.serverroot }} 
      -DSYSCONFDIR={{ mysql.serverroot }}/etc 
      -DMYSQL_UNIX_ADDR={{ mysql.conf.socket }}
      -DDEFAULT_CHARSET=utf8 
      -DDEFAULT_COLLATION=utf8_general_ci
    creates=CMakeCache.txt

- name: 'compile-src | make MySQL {{ mysql.version }}'
  notify: Restart MySQL
  command: >
    chdir={{ local.src }}/mysql-{{ mysql.version }}
    make
    creates=client/mysql
  register: make_mysql_binary

- name: 'compile-src | make insall MySQL-{{ mysql.version }}'
  when: make_mysql_binary.changed
  notify: Restart MySQL
  command: >
    make install
    chdir={{ local.src }}/mysql-{{ mysql.version }}

