#  __  __       ____   ___  _         ____   ____    ___            _        
# |  \/  |_   _/ ___| / _ \| |       | ___| | ___|  / / |_ __ _ ___| | _____ 
# | |\/| | | | \___ \| | | | |   ____|___ \ |___ \ / /| __/ _` / __| |/ / __|
# | |  | | |_| |___) | |_| | |__|_____|__) | ___) / / | || (_| \__ \   <\__ \
# |_|  |_|\__, |____/ \__\_\_____|   |____(_)____/_/   \__\__,_|___/_|\_\___/
#         |___/                                                              
#                  _                               __ _       
#  _ __ ___   __ _| | _____        ___ ___  _ __  / _(_) __ _ 
# | '_ ` _ \ / _` | |/ / _ \_____ / __/ _ \| '_ \| |_| |/ _` |
# | | | | | | (_| |   <  __/_____| (_| (_) | | | |  _| | (_| |
# |_| |_| |_|\__,_|_|\_\___|      \___\___/|_| |_|_| |_|\__, |
#                                                       |___/ 
- name: 'Each directory should be created in {{ mysql.serverroot }}'
  file: >
    path={{ mysql.serverroot }}/{{ item }} 
    mode=0755
    owner={{ mysql.user.username }} 
    group={{ mysql.user.group }}
    state=directory 
  with_items:
    - etc
    - data
    - dump
    - var/run
    - var/log

- name: 'Be sure {{ mysql.serverroot }} is owned by {{ mysql.user.username }}'
  file: >
    path={{ mysql.serverroot }}
    owner={{ mysql.user.username }}
    group={{ mysql.user.group }}
    state=directory

- name: 'Be sure MySQL database is installed'
  command: >
    chdir={{ mysql.serverroot }}
    {{ mysql.serverroot }}/scripts/mysql_install_db 
      --user={{ mysql.user.username }}
      --basedir={{ mysql.serverroot }} 
      --datadir={{ mysql.serverroot }}/data
    creates=data/mysql/db.MYI
  register: install_mysql_database

