#           _ _                              __  __ 
#  ___  ___| (_)_ __  _   ___  __      ___  / _|/ _|
# / __|/ _ \ | | '_ \| | | \ \/ /____ / _ \| |_| |_ 
# \__ \  __/ | | | | | |_| |>  <_____| (_) |  _|  _|
# |___/\___|_|_|_| |_|\__,_/_/\_\     \___/|_| |_|  
#                                                   
- hosts: all
  user:  root
  sudo:  True
  tasks:
    - name: selinux-off | RedHat | libselinux-python should be installed
      when: ansible_os_family == "RedHat"
      yum:  name=libselinux-python state=present

    - name: selinux-off | Debian | python-selinux should be installed
      when: ansible_os_family == "Debian"
      apt:  name=python-selinux state=present

    - name: selinux-off | Disable SELinux
      when: ansible_os_family in [ 'RedHat', 'Debian' ]
      selinux: state=disabled

