#      _            _                                       
#   __| | ___ _ __ | | ___  _   _       _   _ ___  ___ _ __ 
#  / _` |/ _ \ '_ \| |/ _ \| | | |_____| | | / __|/ _ \ '__|
# | (_| |  __/ |_) | | (_) | |_| |_____| |_| \__ \  __/ |   
#  \__,_|\___| .__/|_|\___/ \__, |      \__,_|___/\___|_|   
#            |_|            |___/                           
- hosts: all
  become: True
  become_user: root
  remote_user: root
  vars:
    conf:
      home: /home
    user:
      username: deploy
      password: $5$cNynTWN1$UFS1hSpKKOHcArUeHwypn9SQKz19oC7DOVCwUTEzUFB
      group: deploy
      uid: 400
      gid: 400
  tasks:
    - name: deploy-user | Group for deployment should be created
      group: >
        name={{ user.username }}
        gid={{ user.gid }}
        state=present

    - name: deploy-user | User for deployment should be created
      user: >
        name={{ user.username }}
        uid={{ user.uid }}
        group={{ user.group }}
        groups=wheel
        shell=/bin/sh
        home={{ conf.home }}/{{ user.username }}
        password={{ user.password }}
        createhome=yes
        state=present

    - name: deploy-user | Vagrant | vagrant should belong to deploy group
      when: ansible_product_name == "VirtualBox" and
            ( ansible_env.SUDO_USER == "vagrant" or ansible_user_id == "vagrant" )
      user: name=vagrant groups="wheel,{{ user.group}}" state=present


    - name: deploy-user | Linux | sudoers.d/deploy has been created
      when: ansible_system == "Linux"
      shell: >
        chdir=/etc/sudoers.d
        creates=deploy
        printf "Defaults secure_path = '%s'\n%%%s ALL=NOPASSWD%s ALL\n"
        '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
        {{ user.group }} : | tr "'" '"' > deploy

    - name: deploy-user | Linux | sudoers.d/deploy is 0440
      when: ansible_system == "Linux"
      file: path=/etc/sudoers.d/deploy mode=0440 state=file

    - name: deploy-user | FreeBSD | sudoers.d/deploy has been created
      when: ansible_os_family == "FreeBSD"
      shell: >
        chdir=/usr/local/etc/sudoers.d
        creates=deploy
        printf "Defaults secure_path = '%s'\n%%%s ALL=NOPASSWD%s ALL\n"
        '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
        {{ user.group }} : | tr "'" '"' > deploy

    - name: deploy-user | FreeBSD | sudoers.d/deploy is 0440
      when: ansible_os_family == "FreeBSD"
      file: path=/usr/local/etc/sudoers.d/deploy mode=0440 state=file

    - name: deploy-user | OpenBSD | Check /etc/sudoers
      when: ansible_system == "OpenBSD"
      shell: grep %{{ user.group }} /etc/sudoers
      register: sudoers
      ignore_errors: True
      changed_when: sudoers.rc == 1

    - name: deploy-user | {{ user.group }} should be registered in /etc/sudoers
      when: sudoers.changed
      ignore_errors: True
      shell: >
        printf "%%%s ALL=NOPASSWD%s ALL\n" {{ user.group }} : >> /etc/sudoers

    - name: deploy-user | Authorized key should be deployed
      authorized_key: >
        user={{ user.username }}
        key="{{ lookup('file', '../.ssh/ssh.deploy-rsa.pub') }}"


