#                  _       _                     _         _ 
#  _   _ _ __   __| | __ _| |_ ___       ___ ___| |__   __| |
# | | | | '_ \ / _` |/ _` | __/ _ \_____/ __/ __| '_ \ / _` |
# | |_| | |_) | (_| | (_| | ||  __/_____\__ \__ \ | | | (_| |
#  \__,_| .__/ \__,_|\__,_|\__\___|     |___/___/_| |_|\__,_|
#       |_|                                                  
- hosts: all
  become: True
  become_user: root
  remote_user: deploy
  vars:
    sshd:
      port: __SSHDPORT__
      rootlogin: 'no'
  tasks:
    - name: update-sshd | Enable Port setting in /etc/ssh/sshd_config
      notify: Restart SSHD
      replace:
        backup=yes
        dest=/etc/ssh/sshd_config
        regexp='^#Port (.+)'
        replace='Port \1'
        validate='sshd -t -f %s'

    - name: update-sshd | Change sshd port setting
      when: sshd.port > 0 and sshd.port < 65535
      notify: Restart SSHD
      register: rewrite_sshd_config
      replace:
        backup=yes
        dest=/etc/ssh/sshd_config
        regexp='^Port .+$'
        replace='Port {{ sshd.port }}'
        validate='sshd -t -f %s'

    - name: update-sshd | Enable PermitRootLogin settings in /etc/ssh/sshd_config
      notify: Restart SSHD
      replace:
        backup=yes
        dest=/etc/ssh/sshd_config
        regexp='^#PermitRootLogin (.+)'
        replace='PermitRootLogin \1'
        validate='sshd -t -f %s'

    - name: update-sshd | Change PermitRootLogin setting
      when: rewrite_sshd_config|changed
      notify: Restart SSHD
      replace:
        backup=yes
        dest=/etc/ssh/sshd_config
        regexp='^PermitRootLogin .+$'
        replace='PermitRootLogin {{ sshd.rootlogin }}'
        validate='sshd -t -f %s'

  handlers:
    - name: Restart SSHD
      service: name=sshd state=restarted

