#                  _                                           
#  _ __ ___   __ _| | _____       ___  ___ _ ____   _____ _ __ 
# | '_ ` _ \ / _` | |/ / _ \_____/ __|/ _ \ '__\ \ / / _ \ '__|
# | | | | | | (_| |   <  __/_____\__ \  __/ |   \ V /  __/ |   
# |_| |_| |_|\__,_|_|\_\___|     |___/\___|_|    \_/ \___|_|   
#                                                              
- hosts: vm
  become: True
  become_user: root
  remote_user: deploy
  roles:
    - common
    - src/firewall
    - src/openssl
    - src/perl
    - src/cpanm
    - src/bind-9
    - src/apache-2.2
    - src/nginx
    - rpm/munin-cron
    - rpm/munin-node
    - pkg/munin/httpd
    - src/mysql-5.5
    - src/opensmtpd
    - src/postgresql
    - src/php-5.3
    - src/php-5.5
    - src/phpmyadmin
    - src/dovecot
    - src/sendmail-local
    - src/sendmail-system
    - rpm/svnserve
    - src/netqmail
    - src/vsftpd
    - cleanup
