#  _           _ _     _                            _     _                 
# | |__  _   _(_) | __| |      _ __ ___   __ _  ___| |__ (_)_ __   ___  ___ 
# | '_ \| | | | | |/ _` |_____| '_ ` _ \ / _` |/ __| '_ \| | '_ \ / _ \/ __|
# | |_) | |_| | | | (_| |_____| | | | | | (_| | (__| | | | | | | |  __/\__ \
# |_.__/ \__,_|_|_|\__,_|     |_| |_| |_|\__,_|\___|_| |_|_|_| |_|\___||___/
#                                                                           
- hosts: all
  become: True
  become_user: root
  remote_user: deploy
  roles:
    - bootstrap
    - env/selinux
    - role1-you-want-to-execute
    - role2-you-want-to-execute
    - cleandown

