#  ____           _                 ____   ___  _        ___            _        
# |  _ \ ___  ___| |_ __ _ _ __ ___/ ___| / _ \| |      / / |_ __ _ ___| | _____ 
# | |_) / _ \/ __| __/ _` | '__/ _ \___ \| | | | |     / /| __/ _` / __| |/ / __|
# |  __/ (_) \__ \ || (_| | | |  __/___) | |_| | |___ / / | || (_| \__ \   <\__ \
# |_|   \___/|___/\__\__, |_|  \___|____/ \__\_\_____/_/   \__\__,_|___/_|\_\___/
#                    |___/                                                       
# install-pkg
- name: install-pkg | Install dependencies for PostgreSQL {{ postgresql.version }}
  when: ansible_os_family == "RedHat"
  yum:  name={{ item }} state=present
  with_items:
    - python-psycopg2

