#  ____  _   _ ____      ____   _____   __                    
# |  _ \| | | |  _ \    | ___| |___ /  / /_   ____ _ _ __ ___ 
# | |_) | |_| | |_) |___|___ \   |_ \ / /\ \ / / _` | '__/ __|
# |  __/|  _  |  __/_____|__) | ___) / /  \ V / (_| | |  \__ \
# |_|   |_| |_|_|       |____(_)____/_/    \_/ \__,_|_|  |___/
#                                                             
php:
  rebuild: False
  version: 5.3.27
  install: /usr/local
  buildat: /usr/local/src
  depends:
    apache: { serverroot: '/opt/httpd' }
    mysql:  { serverroot: '/opt/mysql', socket: '/tmp/mysql.sock' }
    libgd:  { version: 2.0.33, install: '/usr/local' }

