#                        _          __                      __                    
#  _ __ ___  _   _ _ __ (_)_ __    / /__ _ __ ___  _ __    / /_   ____ _ _ __ ___ 
# | '_ ` _ \| | | | '_ \| | '_ \  / / __| '__/ _ \| '_ \  / /\ \ / / _` | '__/ __|
# | | | | | | |_| | | | | | | | |/ / (__| | | (_) | | | |/ /  \ V / (_| | |  \__ \
# |_| |_| |_|\__,_|_| |_|_|_| |_/_/ \___|_|  \___/|_| |_/_/    \_/ \__,_|_|  |___/
#                                                                                 
munin:
  cron:
    enabeld: True
    workingdir: /usr/local/src
    conf:
      dbdir:   /var/lib/munin
      htmldir: /var/www/html/munin
      logdir:  /var/log/munin
      rundir:  /var/run/munin
    packages:
      install: [ 'munin' ]
  httpd:
    enabled: True
    started: True
    rebuild: False
    version: 1.6.1
    serverroot: /opt/munin/httpd
    initscript: munin-httpd
    workingdir: /usr/local/src
    user:
      username: nginx
      password: ''
      uid: 8192
      gid: 8192
      group: nginx
      groups: 
        - { name: httpd, gid: 8001 }
      shell: /sbin/nolgin
      comment: "'nginx httpd server'"
    conf:
      listen: 3384
      servername: 127.0.0.1
      documentroot: /opt/munin/httpd/html

