#  ____  _   _ ____      ____   ____    __                    
# |  _ \| | | |  _ \    | ___| | ___|  / /_   ____ _ _ __ ___ 
# | |_) | |_| | |_) |___|___ \ |___ \ / /\ \ / / _` | '__/ __|
# |  __/|  _  |  __/_____|__) | ___) / /  \ V / (_| | |  \__ \
# |_|   |_| |_|_|       |____(_)____/_/    \_/ \__,_|_|  |___/
#                                                             
php:
  rebuild: False
  version: 5.5.16
  install: '/usr/local'
  inifile: development
  depends:
    apache: { serverroot: '/opt/httpd' }
    mysql:  { serverroot: '/opt/mysql', socket: '/tmp/mysql.sock' }
    libgd:  { version: 2.1.0, install: '/usr/local' }

