#  ____                 _                 _ _    ___            _        
# / ___|  ___ _ __   __| |_ __ ___   __ _(_) |  / / |_ __ _ ___| | _____ 
# \___ \ / _ \ '_ \ / _` | '_ ` _ \ / _` | | | / /| __/ _` / __| |/ / __|
#  ___) |  __/ | | | (_| | | | | | | (_| | | |/ / | || (_| \__ \   <\__ \
# |____/ \___|_| |_|\__,_|_| |_| |_|\__,_|_|_/_/   \__\__,_|___/_|\_\___/
#                                                                        
- include: install-pkg.yml
  when: sendmail.updateonly == False
- include: to-sendmail.yml
  when: ansible_os_family == "RedHat"
- include: create-user.yml
  when: sendmail.updateonly == False
- include: get-archive.yml
- include: compile-src.yml
- include: make-config.yml
  when: sendmail.updateonly == False
- include: set-mailbox.yml
- include: boot-script.yml

