#                        _          __                      __                    
#  _ __ ___  _   _ _ __ (_)_ __    / /__ _ __ ___  _ __    / /_   ____ _ _ __ ___ 
# | '_ ` _ \| | | | '_ \| | '_ \  / / __| '__/ _ \| '_ \  / /\ \ / / _` | '__/ __|
# | | | | | | |_| | | | | | | | |/ / (__| | | (_) | | | |/ /  \ V / (_| | |  \__ \
# |_| |_| |_|\__,_|_| |_|_|_| |_/_/ \___|_|  \___/|_| |_/_/    \_/ \__,_|_|  |___/
#                                                                                 
munin:
  cron:
    workingdir: /usr/local/src
    conf:
      dbdir:   /var/lib/munin
      htmldir: /var/www/html/munin
      logdir:  /var/log/munin
      rundir:  /var/run/munin

