#   ___                   ____  __  __ _____ ____  ____    __                    
#  / _ \ _ __   ___ _ __ / ___||  \/  |_   _|  _ \|  _ \  / /_   ____ _ _ __ ___ 
# | | | | '_ \ / _ \ '_ \\___ \| |\/| | | | | |_) | | | |/ /\ \ / / _` | '__/ __|
# | |_| | |_) |  __/ | | |___) | |  | | | | |  __/| |_| / /  \ V / (_| | |  \__ \
#  \___/| .__/ \___|_| |_|____/|_|  |_| |_| |_|   |____/_/    \_/ \__,_|_|  |___/
#       |_|                                                                      
#
opensmtpd:
  started: True
  rebuild: False
  version: 5.7.1p1
  updateonly: False
  initscript: opensmtpd
  serverroot: /opt/opensmtpd
  workingdir: /usr/local/src
  mtaqueue: /var/spool/queues
  msaqueue: /var/spool/cqueue 
  files:
    dbmap:
      - aliases
      - authinfo
      - relayhosts
      - virtdomains
      - virtusers
  packages:
    freebsd:
      install: [
        'autoconf', 'automake', 'bison', 'byacc', 'cyrus-sasl', 'cyrus-sasl-gssapi',
        'cyrus-sasl-saslauthd', 'db48', 'gcc', 'libasr', 'libevent2', 'libtool',
        'openssl', 'pcre'
      ]
    redhat:
      install: [
        'autoconf', 'automake', 'bison', 'byacc', 'cyrus-sasl-lib', 'cyrus-sasl-devel',
        'cyrus-sasl-md5', 'cyrus-sasl-plain', 'cyrus-sasl-ntlm', 'db4', 'db4-devel',
        'db4-utils', 'gcc', 'gcc-c++', 'libevent-devel', 'libtool', 'openssl-devel',
        'pcre', 'pcre-devel', 'zlib-devel'
      ]
  user:
    daemon:
      username: _smtpd
      group: _smtpd
      uid: 6309
      gid: 6309
      home: /var/empty
      shell: /sbin/nologin
      comment: '"SMTP Daemon"'
    queue:
      username: _smtpq
      group: _smtpq
      uid: 6310
      gid: 6310
      home: /var/empty
      shell: /sbin/nologin
      comment: '"SMTP Queue"'
    mda:
      username: virtmail
      uid: 660
      gid: 660
      home: /home/virtmail
      group: virtmail
      shell: /bin/sh
      comment: "'Virtual Mailbox'"
maildrop:
  rebuild: False
  version: 2.8.3
  install: /opt/opensmtpd

