#             __ _             _    ___            _        
# __   _____ / _| |_ _ __   __| |  / / |_ __ _ ___| | _____ 
# \ \ / / __| |_| __| '_ \ / _` | / /| __/ _` / __| |/ / __|
#  \ V /\__ \  _| |_| |_) | (_| |/ / | || (_| \__ \   <\__ \
#   \_/ |___/_|  \__| .__/ \__,_/_/   \__\__,_|___/_|\_\___/
#                   |_|                                     
- include: install-pkg.yml
  when: vsftpd.updateonly == False
- include: create-user.yml
  when: vsftpd.updateonly == False
- include: get-archive.yml
- include: compile-src.yml
- include: make-config.yml
  when: vsftpd.updateonly == False
- include: boot-script.yml
- include: load-module.yml
  when: vsftpd.updateonly == False

- name: Start vsftpd Server
  when: vsftpd.started == True
  service: name={{ vsftpd.initscript }} state=started

- name: Stop vsftpd Server
  when: vsftpd.started == False
  service: name={{ vsftpd.initscript }} state=stopped

