#   __ _                        _ _    ___            _        
#  / _(_)_ __ _____      ____ _| | |  / / |_ __ _ ___| | _____ 
# | |_| | '__/ _ \ \ /\ / / _` | | | / /| __/ _` / __| |/ / __|
# |  _| | | |  __/\ V  V / (_| | | |/ / | || (_| \__ \   <\__ \
# |_| |_|_|  \___| \_/\_/ \__,_|_|_/_/   \__\__,_|___/_|\_\___/
#                                                              
# compile-src
- name: compile-src | Deploy firewall-script files
  shell: >
    make install
    chdir={{ buildroot }}/firewall-scripts
    creates=/etc/firewall/firewall-rules

