#                        _          __               _         __              _        
#  _ __ ___  _   _ _ __ (_)_ __    / / __   ___   __| | ___   / / __ ___   ___| |_ __ _ 
# | '_ ` _ \| | | | '_ \| | '_ \  / / '_ \ / _ \ / _` |/ _ \ / / '_ ` _ \ / _ \ __/ _` |
# | | | | | | |_| | | | | | | | |/ /| | | | (_) | (_| |  __// /| | | | | |  __/ || (_| |
# |_| |_| |_|\__,_|_| |_|_|_| |_/_/ |_| |_|\___/ \__,_|\___/_/ |_| |_| |_|\___|\__\__,_|
#                                                                                       
dependencies:
  - role: src/perl
  - role: src/cpanm

