#                  _    __                    
#  _ __   ___ _ __| |  / /_   ____ _ _ __ ___ 
# | '_ \ / _ \ '__| | / /\ \ / / _` | '__/ __|
# | |_) |  __/ |  | |/ /  \ V / (_| | |  \__ \
# | .__/ \___|_|  |_/_/    \_/ \__,_|_|  |___/
# |_|                                         
perl:
  rebuild: 0
  version: 5.16.3
  install: '/usr/local'

