#                                             ___            _        
#  _____   ___ __  ___  ___ _ ____   _____   / / |_ __ _ ___| | _____ 
# / __\ \ / / '_ \/ __|/ _ \ '__\ \ / / _ \ / /| __/ _` / __| |/ / __|
# \__ \\ V /| | | \__ \  __/ |   \ V /  __// / | || (_| \__ \   <\__ \
# |___/ \_/ |_| |_|___/\___|_|    \_/ \___/_/   \__\__,_|___/_|\_\___/
#                                                                     
# boot-script
- name: boot-script | Turn on init script
  service: name={{ svnserve.initscript }} enabled=yes

