#                  _    ___            _        
#  _ __   ___ _ __| |  / / |_ __ _ ___| | _____ 
# | '_ \ / _ \ '__| | / /| __/ _` / __| |/ / __|
# | |_) |  __/ |  | |/ / | || (_| \__ \   <\__ \
# | .__/ \___|_|  |_/_/   \__\__,_|___/_|\_\___/
# |_|                                           
# compile-src
#
- name: compile-src | REBUILD | make clean
  when: perl.rebuild == True
  shell: >
    chdir={{ perl.workingdir }}/perl-{{ perl.version }}/
    removes=Makefile
    make clean distclean

- name: compile-src | Perl {{ perl.version }} should be configured
  shell: >
    chdir={{ perl.workingdir }}/perl-{{ perl.version }}/
    creates=Makefile
    /bin/sh Configure -des -Dprefix={{ perl.install }}

- name: compile-src | make Perl {{ perl.version }}
  command: >
    chdir={{ perl.workingdir }}/perl-{{ perl.version }}/
    creates=perl
    make
  register: make_perl_binary

- name: compile-src | make test
  when: make_perl_binary.changed
  command: >
    chdir={{ perl.workingdir }}/perl-{{ perl.version }}/
    make test

- name: compile-src | make install perl {{ perl.version }}
  when: make_perl_binary.changed
  command: >
    chdir={{ perl.workingdir }}/perl-{{ perl.version }}/
    make install

