#                  _    ___            _        
#  _ __   ___ _ __| |  / / |_ __ _ ___| | _____ 
# | '_ \ / _ \ '__| | / /| __/ _` / __| |/ / __|
# | |_) |  __/ |  | |/ / | || (_| \__ \   <\__ \
# | .__/ \___|_|  |_/_/   \__\__,_|___/_|\_\___/
# |_|                                           
#                  _                                  _       _      
#  _ __ ___   __ _| | _____       _ __ ___   ___   __| |_   _| | ___ 
# | '_ ` _ \ / _` | |/ / _ \_____| '_ ` _ \ / _ \ / _` | | | | |/ _ \
# | | | | | | (_| |   <  __/_____| | | | | | (_) | (_| | |_| | |  __/
# |_| |_| |_|\__,_|_|\_\___|     |_| |_| |_|\___/ \__,_|\__,_|_|\___|
#                                                                    
- name: 'Download cpanm'
  get_url: >
    url='http://xrl.us/cpanm';
    dest={{ local.src }}/cpanm

- name: 'Install cpanm = {{ local.dir }}/bin/cpanm'
  shell: >
    chdir={{ local.src }}
    install -o root -m 0755 cpanm {{ local.dir }}/bin
    creates={{ local.dir }}/bin/cpanm

