#        _                                 _           _          ___            _        
#  _ __ | |__  _ __  _ __   __ _  __ _  __| |_ __ ___ (_)_ __    / / |_ __ _ ___| | _____ 
# | '_ \| '_ \| '_ \| '_ \ / _` |/ _` |/ _` | '_ ` _ \| | '_ \  / /| __/ _` / __| |/ / __|
# | |_) | | | | |_) | |_) | (_| | (_| | (_| | | | | | | | | | |/ / | || (_| \__ \   <\__ \
# | .__/|_| |_| .__/| .__/ \__, |\__,_|\__,_|_| |_| |_|_|_| |_/_/   \__\__,_|___/_|\_\___/
# |_|         |_|   |_|    |___/                                                          
# get-archive.yml
- name: get-archive | Deploy phpPgAdmin-{{ phppgadmin.version }}.tar.gz
  copy: >
    src=phpPgAdmin-{{ phppgadmin.version }}.tar.gz
    dest={{ buildroot }}/phpPgAdmin-{{ phppgadmin.version }}.tar.gz

- name: get-archive | Extract {{ buildroot }}/phpPgAdmin-{{ phppgadmin.version }}.tar.gz
  unarchive: >
    src={{ buildroot }}/phpPgAdmin-{{ phppgadmin.version }}.tar.gz
    dest={{ buildroot }}/
    creates={{ buildroot }}/phpPgAdmin-{{ phppgadmin.version }}
    copy=no

