#  ____           _                 ____   ___  _        ___            _        
# |  _ \ ___  ___| |_ __ _ _ __ ___/ ___| / _ \| |      / / |_ __ _ ___| | _____ 
# | |_) / _ \/ __| __/ _` | '__/ _ \___ \| | | | |     / /| __/ _` / __| |/ / __|
# |  __/ (_) \__ \ || (_| | | |  __/___) | |_| | |___ / / | || (_| \__ \   <\__ \
# |_|   \___/|___/\__\__, |_|  \___|____/ \__\_\_____/_/   \__\__,_|___/_|\_\___/
#                    |___/                                                       
# boot-script
- name: boot-script | RedHat | Deploy /etc/init.d/{{ postgresql.initscript }}
  when: ansible_os_family == "RedHat"
  template: >
    src=etc/init.d/postgresql.RedHat.j2
    dest=/etc/rc.d/init.d/{{ postgresql.initscript }}
    mode=0755
    owner=root
    group=root

- name: boot-script | RedHat | Install /etc/rc.d/init.d/{{ postgresql.initscript }}
  when: ansible_os_family == "RedHat"
  shell: >
    /sbin/chkconfig --add {{ postgresql.initscript }}
    creates=/etc/rc.d/rc0.d/K36{{ postgresql.initscript }}

- name: boot-script | Turn on init script
  service: name={{ postgresql.initscript }} enabled=yes

