#              _                ___            _        
#  _ __   __ _(_)_ __ __  __   / / |_ __ _ ___| | _____ 
# | '_ \ / _` | | '_ \\ \/ /  / /| __/ _` / __| |/ / __|
# | | | | (_| | | | | |>  <  / / | || (_| \__ \   <\__ \
# |_| |_|\__, |_|_| |_/_/\_\/_/   \__\__,_|___/_|\_\___/
#        |___/                                          
# boot-script
#
- name: 'boot-script | RedHat | Deploy /etc/init.d/nginx'
  when: ansible_os_family == "RedHat"
  template: >
    src=etc/init.d/nginx.RedHat.j2
    dest=/etc/init.d/nginx
    mode=0755
    owner=root
    group=root

- name: 'boot-script | RedHat | Install /etc/rc.d/init.d/nginx'
  when: ansible_os_family == "RedHat"
  shell: >
    /sbin/chkconfig --add nginx
    creates=/etc/rc.d/rc0.d/K15nginx

- name: 'boot-script | Turn on init script'
  service: name=nginx enabled=yes

