#              _                ___            _        
#  _ __   __ _(_)_ __ __  __   / / |_ __ _ ___| | _____ 
# | '_ \ / _` | | '_ \\ \/ /  / /| __/ _` / __| |/ / __|
# | | | | (_| | | | | |>  <  / / | || (_| \__ \   <\__ \
# |_| |_|\__, |_|_| |_/_/\_\/_/   \__\__,_|___/_|\_\___/
#        |___/                                          
#                  _                               __ _       
#  _ __ ___   __ _| | _____        ___ ___  _ __  / _(_) __ _ 
# | '_ ` _ \ / _` | |/ / _ \_____ / __/ _ \| '_ \| |_| |/ _` |
# | | | | | | (_| |   <  __/_____| (_| (_) | | | |  _| | (_| |
# |_| |_| |_|\__,_|_|\_\___|      \___\___/|_| |_|_| |_|\__, |
#                                                       |___/ 
- name: 'Be sure the directory for virtual hosts exists'
  file: >
    path={{ nginx.serverroot }}/conf/virthost
    mode=0755
    state=directory
    owner=root
    group=root

- name: 'Deploy {{ nginx.serverroot }}/conf/nginx.conf'
  notify: Restart nginx
  template: >
    src=nginx.conf.j2
    dest={{ nginx.serverroot }}/conf/nginx.conf

- name: 'Deploy {{ nginx.serverroot }}/conf/virthost/example.jp.conf'
  notify: Restart nginx
  template: >
    src=virthost-example.jp.conf.j2
    dest={{ nginx.serverroot }}/conf/virthost/example.jp.conf

