#                        _ _    ___            _        
#   __ _ _ __ ___   __ _(_) |  / / |_ __ _ ___| | _____ 
#  / _` | '_ ` _ \ / _` | | | / /| __/ _` / __| |/ / __|
# | (_| | | | | | | (_| | | |/ / | || (_| \__ \   <\__ \
#  \__, |_| |_| |_|\__,_|_|_/_/   \__\__,_|___/_|\_\___/
#     |_|                                               
# get-archive
- name: get-archive | Download qmail {{ qmail.version }} at {{ buildroot }}
  get_url: >
    url=http://www.qmail.org/netqmail-{{ qmail.version }}.tar.gz
    dest={{ buildroot }}/netqmail-{{ qmail.version }}.tar.gz

- name: get-archive | Extract {{ buildroot }}/qmail-{{ qmail.version }}
  unarchive: >
    src={{ buildroot }}/netqmail-{{ qmail.version }}.tar.gz
    dest={{ buildroot }}
    creates={{ buildroot }}/netqmail-{{ qmail.version }}
    copy=no

- name: get-archive | Download tcp server at {{ buildroot }}
  get_url: >
    url=http://cr.yp.to/ucspi-tcp/ucspi-tcp-0.88.tar.gz
    dest={{ buildroot }}/ucspi-tcp-0.88.tar.gz

- name: get-archive | Extract {{ buildroot }}/ucspi-tcp-0.88.tar.gz
  unarchive: >
    src={{ buildroot }}/ucspi-tcp-0.88.tar.gz
    dest={{ buildroot }}
    creates={{ buildroot }}/ucspi-tcp-0.88
    copy=no

