#                   _     _                            _ 
#   ___ _ __   __ _| |__ | | ___        ___ _ __   ___| |
#  / _ \ '_ \ / _` | '_ \| |/ _ \_____ / _ \ '_ \ / _ \ |
# |  __/ | | | (_| | |_) | |  __/_____|  __/ |_) |  __/ |
#  \___|_| |_|\__,_|_.__/|_|\___|      \___| .__/ \___|_|
#                                          |_|           
#
- hosts: vm
  user:  root
  sudo:  True
  vars:
    epelserver: 'http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel'
    remiserver: 'http://rpms.famillecollet.com/enterprise'
  tasks:
    - name: enable-epel | RedHat | Install EPEL repository/v6
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == 5
      shell: >
        creates=/etc/yum.repos.d/epel.repo
        rpm -hUv {{ epelserver }}/5/{{ ansible_machine }}/epel-release-5-4.noarch.rpm

    - name: enable-epel | RedHat | Install EPEL repository/v6
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == 6
      shell: >
        creates=/etc/yum.repos.d/epel.repo
        rpm -hUv {{ epelserver }}/fedora/epel/6/{{ ansible_machine }}/epel-release-6-8.noarch.rpm

    - name: enable-remi | RedHat | Install Remi repository
      when: ansible_distribution == "CentOS"
      shell: >
        creates=/etc/yum.repos.d/remi.repo
        rpm -hUv {{ remiserver }}/remi-release-{{ ansible_distribution_major_version }}.rpm

