#             __ _             _    ___            _        
# __   _____ / _| |_ _ __   __| |  / / |_ __ _ ___| | _____ 
# \ \ / / __| |_| __| '_ \ / _` | / /| __/ _` / __| |/ / __|
#  \ V /\__ \  _| |_| |_) | (_| |/ / | || (_| \__ \   <\__ \
#   \_/ |___/_|  \__| .__/ \__,_/_/   \__\__,_|___/_|\_\___/
#                   |_|                                     
# compile-src
- name: 'compile-src | REBUILD | make clean'
  command: >
    make clean
    chdir={{ local.src }}/vsftpd-{{ vsftpd.version }}/
    removes=vsftpd
  when: vsftpd.rebuild == 1

- name: 'compile-src | Patches should be copied'
  template: >
    src=usr/local/src/{{ item }}.j2
    dest={{ local.src }}/vsftpd-{{ vsftpd.version }}/{{ item }}
  with_items: vsftpd.patches

- name: 'compile-src | Patches should have been applied'
  shell: >
    patch -p0 < {{ item }}
    chdir={{ local.src }}/vsftpd-{{ vsftpd.version }}/
    creates={{ item }}.ok
  with_items: vsftpd.patches

- name: 'compile-src | make vsftpd {{ vsftpd.version }}'
  notify: Restart vsftpd
  command: >
    make
    chdir={{ local.src }}/vsftpd-{{ vsftpd.version }}/
    creates=vsftpd
  register: make_vsftpd_binary

- name: 'compile-src | make install vsftpd {{ vsftpd.version }}'
  when: make_vsftpd_binary.changed
  notify: Restart vsftpd
  command: >
    make install
    chdir={{ local.src }}/vsftpd-{{ vsftpd.version }}/

