#             __ _             _    ___            _        
# __   _____ / _| |_ _ __   __| |  / / |_ __ _ ___| | _____ 
# \ \ / / __| |_| __| '_ \ / _` | / /| __/ _` / __| |/ / __|
#  \ V /\__ \  _| |_| |_) | (_| |/ / | || (_| \__ \   <\__ \
#   \_/ |___/_|  \__| .__/ \__,_/_/   \__\__,_|___/_|\_\___/
#                   |_|                                     
# compile-src
- name: compile-src | REBUILD | make clean
  when: vsftpd.rebuild == True
  command: >
    chdir={{ vsftpd.workingdir }}/vsftpd-{{ vsftpd.version }}/
    removes=vsftpd
    make clean

- name: compile-src | Patches should be copied
  with_items: vsftpd.patches
  template: >
    src=usr/local/src/{{ item }}.j2
    dest={{ vsftpd.workingdir }}/vsftpd-{{ vsftpd.version }}/{{ item }}

- name: compile-src | Patches should have been applied
  with_items: vsftpd.patches
  shell: >
    chdir={{ vsftpd.workingdir }}/vsftpd-{{ vsftpd.version }}/
    creates={{ item }}.ok
    patch -p0 < {{ item }}

- name: compile-src | make vsftpd {{ vsftpd.version }}
  notify: Restart vsftpd
  register: make_vsftpd_binary
  command: >
    chdir={{ vsftpd.workingdir }}/vsftpd-{{ vsftpd.version }}/
    creates=vsftpd
    make

- name: compile-src | make install vsftpd {{ vsftpd.version }}
  when: make_vsftpd_binary.changed
  notify: Restart vsftpd
  command: >
    chdir={{ vsftpd.workingdir }}/vsftpd-{{ vsftpd.version }}/
    make install

