#             __ _             _    ___            _        
# __   _____ / _| |_ _ __   __| |  / / |_ __ _ ___| | _____ 
# \ \ / / __| |_| __| '_ \ / _` | / /| __/ _` / __| |/ / __|
#  \ V /\__ \  _| |_| |_) | (_| |/ / | || (_| \__ \   <\__ \
#   \_/ |___/_|  \__| .__/ \__,_/_/   \__\__,_|___/_|\_\___/
#                   |_|                                     
# create-user
- name: 'create-user | Group {{ vsftpd.user.group }} should be created'
  group: >
    name={{ vsftpd.user.group }}
    gid={{ vsftpd.user.gid }}
    state=present

- name: 'create-user | User {{ vsftpd.user.username }} should be created'
  user: >
    name={{ vsftpd.user.username }} 
    uid={{ vsftpd.user.uid }}
    group={{ vsftpd.user.group }} 
    shell={{ vsftpd.user.shell }}
    home={{ vsftpd.serverroot }}
    comment={{ vsftpd.user.comment }}
    createhome=no
    state=present

