#             __ _             _    ___            _        
# __   _____ / _| |_ _ __   __| |  / / |_ __ _ ___| | _____ 
# \ \ / / __| |_| __| '_ \ / _` | / /| __/ _` / __| |/ / __|
#  \ V /\__ \  _| |_| |_) | (_| |/ / | || (_| \__ \   <\__ \
#   \_/ |___/_|  \__| .__/ \__,_/_/   \__\__,_|___/_|\_\___/
#                   |_|                                     
#                  _                               __ _       
#  _ __ ___   __ _| | _____        ___ ___  _ __  / _(_) __ _ 
# | '_ ` _ \ / _` | |/ / _ \_____ / __/ _ \| '_ \| |_| |/ _` |
# | | | | | | (_| |   <  __/_____| (_| (_) | | | |  _| | (_| |
# |_| |_| |_|\__,_|_|\_\___|      \___\___/|_| |_|_| |_|\__, |
#                                                       |___/ 
- name: 'Each sub directory must exist in {{ vsftpd.serverroot }}'
  file: >
    path={{ vsftpd.serverroot }}/{{ item }}
    mode=0755
    state=directory
    owner=root
    group=root
  with_items: [ 'etc', 'var/run', 'var/log', 'var/empty' ]

- name: 'Deploy {{ vsftpd.serverroot }}/etc/vsftpd.conf'
  notify: Restart vsftpd
  template: >
    src=vsftpd.conf.j2
    dest={{ vsftpd.serverroot }}/etc/vsftpd.conf
    mode=0644
    owner=root
    group=root

- name: 'Deploy {{ vsftpd.serverroot }}/etc/ftp-users'
  template: >
    src=ftp-users.j2
    dest={{ vsftpd.serverroot }}/etc/ftp-users
    mode=0644
    owner=root
    group=root

