#             __ _             _    ___            _        
# __   _____ / _| |_ _ __   __| |  / / |_ __ _ ___| | _____ 
# \ \ / / __| |_| __| '_ \ / _` | / /| __/ _` / __| |/ / __|
#  \ V /\__ \  _| |_| |_) | (_| |/ / | || (_| \__ \   <\__ \
#   \_/ |___/_|  \__| .__/ \__,_/_/   \__\__,_|___/_|\_\___/
#                   |_|                                     
# make-config
- name: make-config | Each sub directory must exist in {{ vsftpd.serverroot }}
  file: >
    path={{ vsftpd.serverroot }}/{{ item }}
    mode=0755
    state=directory
    owner=root
    group=root
  with_items: [ 'etc', 'var/run', 'var/log', 'var/empty' ]

- name: make-config | Deploy {{ vsftpd.serverroot }}/etc/vsftpd.conf
  notify: Restart vsftpd
  template: >
    src=opt/vsftpd/etc/vsftpd.conf.j2
    dest={{ vsftpd.serverroot }}/etc/vsftpd.conf
    mode=0644
    owner=root
    group=root

- name: make-config | Deploy {{ vsftpd.serverroot }}/etc/ftp-users
  template: >
    src=opt/vsftpd/etc/ftp-users.j2
    dest={{ vsftpd.serverroot }}/etc/ftp-users
    mode=0644
    owner=root
    group=root

- name: make-config | Deploy /etc/logrotate.d/vsftpd
  template: >
    src=etc/logrotate.d/vsftpd.j2
    dest=/etc/logrotate.d/vsftpd
    mode=0644
    owner=root
    group=root

