#   ___                   ____  __  __ _____ ____  ____    ___            _        
#  / _ \ _ __   ___ _ __ / ___||  \/  |_   _|  _ \|  _ \  / / |_ __ _ ___| | _____ 
# | | | | '_ \ / _ \ '_ \\___ \| |\/| | | | | |_) | | | |/ /| __/ _` / __| |/ / __|
# | |_| | |_) |  __/ | | |___) | |  | | | | |  __/| |_| / / | || (_| \__ \   <\__ \
#  \___/| .__/ \___|_| |_|____/|_|  |_| |_| |_|   |____/_/   \__\__,_|___/_|\_\___/
#       |_|                                                                        
# boot-script
- name: boot-script | RedHat | Deploy /etc/init.d/{{ opensmtpd.initscript }}
  when: ansible_os_family == "RedHat"
  template: >
    src=etc/init.d/opensmtpd.RedHat.j2
    dest=/etc/init.d/{{ opensmtpd.initscript }}
    mode=0755
    owner=root
    group=root

- name: boot-script | RedHat | Install /etc/rc.d/init.d/{{ opensmtpd.initscript }}
  when: ansible_os_family == "RedHat"
  shell: >
    /sbin/chkconfig --add {{ opensmtpd.initscript }}
    creates=/etc/rc.d/rc0.d/K30{{ opensmtpd.initscript }}

- name: boot-script | FreBSD | Deploy /usr/local/etc/rc.d/{{ opensmtpd.initscript }}
  when: ansible_os_family == "FreeBSD"
  template: >
    src=etc/init.d/opensmtpd.FreeBSD.j2
    dest=/usr/local/etc/rc.d/{{ opensmtpd.initscript }}
    mode=0755
    owner=root
    group=wheel

- name: boot-script | Turn on init script
  service: name={{ opensmtpd.initscript }} enabled=yes

- name: boot-script | Stop sendmail
  service: name=sendmail state=stopped

- name: boot-script | Turn off sendmail
  service: name=sendmail enabled=no

- name: boot-script | Start OpenSMTPD
  when: opensmtpd.started == True
  service: name={{ opensmtpd.initscript }} state=started

- name: boot-script | Stop OpenSMTPD
  when: opensmtpd.started == False
  service: name={{ opensmtpd.initscript }} state=stopped

