#   ___                   ____  __  __ _____ ____  ____    ___            _        
#  / _ \ _ __   ___ _ __ / ___||  \/  |_   _|  _ \|  _ \  / / |_ __ _ ___| | _____ 
# | | | | '_ \ / _ \ '_ \\___ \| |\/| | | | | |_) | | | |/ /| __/ _` / __| |/ / __|
# | |_| | |_) |  __/ | | |___) | |  | | | | |  __/| |_| / / | || (_| \__ \   <\__ \
#  \___/| .__/ \___|_| |_|____/|_|  |_| |_| |_|   |____/_/   \__\__,_|___/_|\_\___/
#       |_|                                                                        
# install-pkg
- name: install-pkg | FreeBSD | Packages required by OpenSMTPD should be installed
  when: ansible_os_family == "FreeBSD"
  pkgng: name={{ item }} state=present
  with_items: opensmtpd.packages.freebsd.install

- name: install-pkg | RedHat | Packages required by OpenSMTPD should be installed
  when: ansible_os_family == "RedHat"
  yum:  name={{ item }} state=present
  with_items: opensmtpd.packages.freebsd.install

