#   ___                   ____  __  __ _____ ____  ____    ___            _        
#  / _ \ _ __   ___ _ __ / ___||  \/  |_   _|  _ \|  _ \  / / |_ __ _ ___| | _____ 
# | | | | '_ \ / _ \ '_ \\___ \| |\/| | | | | |_) | | | |/ /| __/ _` / __| |/ / __|
# | |_| | |_) |  __/ | | |___) | |  | | | | |  __/| |_| / / | || (_| \__ \   <\__ \
#  \___/| .__/ \___|_| |_|____/|_|  |_| |_| |_|   |____/_/   \__\__,_|___/_|\_\___/
#       |_|                                                                        
# make-config
- name: make-config | Deploy {{ opensmtpd.serverroot }}/etc/smtpd.conf
  template: >
    src=opt/opensmtpd/etc/smtpd.conf.j2
    dest={{ opensmtpd.serverroot }}/etc/smtpd.conf
    backup=yes

- name: make-config | create map files in {{ opensmtpd.serverroot }}/etc
  template: >
    src=opt/opensmtpd/etc/{{ item }}.j2
    dest={{ opensmtpd.serverroot }}/etc/{{ item }}
    backup=yes
  with_items: opensmtpd.files.dbmap

- name: make-config | makemap db maps in {{ opensmtpd.serverroot }}/etc
  shell: >
    chdir={{ opensmtpd.serverroot }}
    creates=etc/{{ item }}.db
    ./sbin/makemap etc/{{ item }}
  with_items: opensmtpd.files.dbmap

