#  ____           _                 ____   ___  _        ___            _        
# |  _ \ ___  ___| |_ __ _ _ __ ___/ ___| / _ \| |      / / |_ __ _ ___| | _____ 
# | |_) / _ \/ __| __/ _` | '__/ _ \___ \| | | | |     / /| __/ _` / __| |/ / __|
# |  __/ (_) \__ \ || (_| | | |  __/___) | |_| | |___ / / | || (_| \__ \   <\__ \
# |_|   \___/|___/\__\__, |_|  \___|____/ \__\_\_____/_/   \__\__,_|___/_|\_\___/
#                    |___/                                                       
#                            _ _                         
#   ___ ___  _ __ ___  _ __ (_) | ___       ___ _ __ ___ 
#  / __/ _ \| '_ ` _ \| '_ \| | |/ _ \_____/ __| '__/ __|
# | (_| (_) | | | | | | |_) | | |  __/_____\__ \ | | (__ 
#  \___\___/|_| |_| |_| .__/|_|_|\___|     |___/_|  \___|
#                     |_|                                
- name: '(REBUILD) make clean'
  command: >
    make clean
    chdir={{ local.src }}/postgresql-{{ postgresql.version }}/
    removes=GNUmakefile
  when: postgresql.rebuild == 1

- name: 'Be sure PostgreSQL {{ postgresql.version }} has been configured'
  notify: Restart PostgreSQL
  command: >
    /bin/sh configure
    --prefix={{ postgresql.serverroot }}
    creates=GNUmakefile
    chdir={{ local.src }}/postgresql-{{ postgresql.version }}/

- name: 'make PostgreSQL {{ postgresql.version }}'
  notify: Restart PostgreSQL
  command: >
    make
    chdir={{ local.src }}/postgresql-{{ postgresql.version }}/
    creates=src/bin/pg_ctl/pg_ctl
  register: make_postgresql_binary

- name: 'Be sure PostgreSQL {{ postgresql.version }} is installed'
  when: make_postgresql_binary.changed
  notify: Restart PostgreSQL
  command: >
    make install
    chdir={{ local.src }}/postgresql-{{ postgresql.version }}/


