#  ____           _                 ____   ___  _        ___            _        
# |  _ \ ___  ___| |_ __ _ _ __ ___/ ___| / _ \| |      / / |_ __ _ ___| | _____ 
# | |_) / _ \/ __| __/ _` | '__/ _ \___ \| | | | |     / /| __/ _` / __| |/ / __|
# |  __/ (_) \__ \ || (_| | | |  __/___) | |_| | |___ / / | || (_| \__ \   <\__ \
# |_|   \___/|___/\__\__, |_|  \___|____/ \__\_\_____/_/   \__\__,_|___/_|\_\___/
#                    |___/                                                       
# compile-src
- name: compile-src | REBUILD | make clean
  command: >
    chdir={{ postgresql.workingdir }}/postgresql-{{ postgresql.version }}/
    removes=GNUmakefile
    make clean
  when: postgresql.rebuild == True

- name: compile-src | PostgreSQL {{ postgresql.version }} should be configured
  notify: Restart PostgreSQL
  command: >
    creates=GNUmakefile
    chdir={{ postgresql.workingdir }}/postgresql-{{ postgresql.version }}/
    /bin/sh configure
    --prefix={{ postgresql.serverroot }}

- name: compile-src | make PostgreSQL {{ postgresql.version }}
  notify: Restart PostgreSQL
  command: >
    chdir={{ postgresql.workingdir }}/postgresql-{{ postgresql.version }}/
    creates=src/bin/pg_ctl/pg_ctl
    make
  register: make_postgresql_binary

- name: compile-src | PostgreSQL {{ postgresql.version }} should be installed
  when: make_postgresql_binary.changed
  notify: Restart PostgreSQL
  command: >
    chdir={{ postgresql.workingdir }}/postgresql-{{ postgresql.version }}/
    make install

