#  ____           _                 ____   ___  _        ___            _        
# |  _ \ ___  ___| |_ __ _ _ __ ___/ ___| / _ \| |      / / |_ __ _ ___| | _____ 
# | |_) / _ \/ __| __/ _` | '__/ _ \___ \| | | | |     / /| __/ _` / __| |/ / __|
# |  __/ (_) \__ \ || (_| | | |  __/___) | |_| | |___ / / | || (_| \__ \   <\__ \
# |_|   \___/|___/\__\__, |_|  \___|____/ \__\_\_____/_/   \__\__,_|___/_|\_\___/
#                    |___/                                                       
#                  _                               __ _       
#  _ __ ___   __ _| | _____        ___ ___  _ __  / _(_) __ _ 
# | '_ ` _ \ / _` | |/ / _ \_____ / __/ _ \| '_ \| |_| |/ _` |
# | | | | | | (_| |   <  __/_____| (_| (_) | | | |  _| | (_| |
# |_| |_| |_|\__,_|_|\_\___|      \___\___/|_| |_|_| |_|\__, |
#                                                       |___/ 
- name: 'Be sure {{ postgresql.datadirectory }} should be 0700 permission'
  file: >
    path={{ postgresql.datadirectory }}
    mode=0700
    state=directory
    owner={{ postgresql.user.username }}
    group={{ postgresql.user.group }}

- name: 'Be sure each directory exists'
  file: >
    path={{ postgresql.serverroot }}/{{ item }}
    mode=0755
    state=directory
    owner={{ postgresql.user.username }}
    group={{ postgresql.user.group }}
  with_items:
    - dump
    - logs

- name: 'Be sure {{ postgresql.datadirectory }} should be initialized'
  shell: >
    chdir={{ postgresql.serverroot }}
    sudo -u {{ postgresql.user.username }} 
    -s {{ postgresql.serverroot }}/bin/initdb --no-locale -EUTF-8 -D{{ postgresql.datadirectory }}
    creates={{ postgresql.datadirectory }}/base

- name: 'Deploy configuration files into {{ postgresql.datadirectory }}'
  notify: Restart PostgreSQL
  template: >
    src=data/{{ item }}.j2
    dest={{ postgresql.datadirectory }}/{{ item }}
  with_items:
    - postgresql.conf
    - pg_hba.conf

