#              _                __                    
#  _ __   __ _(_)_ __ __  __   / /_   ____ _ _ __ ___ 
# | '_ \ / _` | | '_ \\ \/ /  / /\ \ / / _` | '__/ __|
# | | | | (_| | | | | |>  <  / /  \ V / (_| | |  \__ \
# |_| |_|\__, |_|_| |_/_/\_\/_/    \_/ \__,_|_|  |___/
#        |___/                                        
nginx:
  started: False
  enabled: True
  rebuild: False
  version: 1.6.1
  updateonly: False
  initscript: nginx
  rotatefile: nginx
  serverroot: /opt/nginx
  workingdir: /usr/local/src
  packages:
    redhat:
      install: [ 'pcre', 'pcre-devel' ]
    debian:
      install: [ 'libpcre3', 'libpcre3-dev' ]
  user:
    username: nginx
    password: ''
    uid: 8192
    gid: 8192
    group: nginx
    groups: 
      - { name: httpd, gid: 8001 }
    shell: /sbin/nolgin
    comment: "'nginx httpd server'"
  conf:
    servername: '127.0.0.1'
    documentroot: '/opt/nginx/html'

