#           _ _                      ___            _        
#  ___  ___| (_)_ __  _   ___  __   / / |_ __ _ ___| | _____ 
# / __|/ _ \ | | '_ \| | | \ \/ /  / /| __/ _` / __| |/ / __|
# \__ \  __/ | | | | | |_| |>  <  / / | || (_| \__ \   <\__ \
# |___/\___|_|_|_| |_|\__,_/_/\_\/_/   \__\__,_|___/_|\_\___/
# make-config
- name: make-config | Redhat | libselinux-python should be installed
  when: ansible_os_family == "RedHat"
  yum:  name=libselinux-python state=present

- name: selinux-off | Debian | python-selinux should be installed
  when: ansible_os_family == "Debian"
  apt:  name=python-selinux state=present

- name: selinux-off | Turn off SELinux
  when: ansible_os_family in [ 'RedHat', 'Debian' ] and selinux.disabled == True
  selinux: state=disabled

- name: selinux-off | Turn on SELinux
  when: ansible_os_family in [ 'RedHat', 'Debian' ] and selinux.disabled == False
  selinux: state=enabled

