#           _ _                      __                    
#  ___  ___| (_)_ __  _   ___  __   / /_   ____ _ _ __ ___ 
# / __|/ _ \ | | '_ \| | | \ \/ /  / /\ \ / / _` | '__/ __|
# \__ \  __/ | | | | | |_| |>  <  / /  \ V / (_| | |  \__ \
# |___/\___|_|_|_| |_|\__,_/_/\_\/_/    \_/ \__,_|_|  |___/
#                                                          
selinux:
  disabled: True

