#  ____                 _                 _ _    ___            _        
# / ___|  ___ _ __   __| |_ __ ___   __ _(_) |  / / |_ __ _ ___| | _____ 
# \___ \ / _ \ '_ \ / _` | '_ ` _ \ / _` | | | / /| __/ _` / __| |/ / __|
#  ___) |  __/ | | | (_| | | | | | | (_| | | |/ / | || (_| \__ \   <\__ \
# |____/ \___|_| |_|\__,_|_| |_| |_|\__,_|_|_/_/   \__\__,_|___/_|\_\___/
#                                                                        
# make-config
#  ____ ____ ____ ____ ____ ____ ____ ____ 
# ||v |||i |||r |||t |||m |||a |||i |||l ||
# ||__|||__|||__|||__|||__|||__|||__|||__||
# |/__\|/__\|/__\|/__\|/__\|/__\|/__\|/__\|
#
- name: make-config | virtmail | Each directory should be created
  file: >
    path={{ procmail.install }}/{{ item }}
    mode=0755
    owner=root
    state=directory
  with_items:
    - etc
    - etc/rcs

#  ____ ____ ____ ____ ____ ____ ____ ____ 
# ||p |||r |||o |||c |||m |||a |||i |||l ||
# ||__|||__|||__|||__|||__|||__|||__|||__||
# |/__\|/__\|/__\|/__\|/__\|/__\|/__\|/__\|
#
- name: make-config | procmail | Log file should be created(1)
  register: procmaillog
  ignore_errors: True
  file: >
    path=/var/log/procmail-local.log
    mode=0600
    owner=root
    state=file

- name: make-config | procmail | Log file should be created(2)
  when: procmaillog|failed
  file: >
    path=/var/log/procmail-local.log
    mode=0600
    owner=root
    state=touch

- name: make-config | procmail spool directory should have been created
  file: >
    path={{ procmail.spool }}
    mode=0770
    owner=root
    group={{ sendmail.user.mta.group }}
    state=directory

#  ____ ____ ____ ____ ____ ____ ____ ____ 
# ||m |||a |||i |||l |||d |||r |||o |||p ||
# ||__|||__|||__|||__|||__|||__|||__|||__||
# |/__\|/__\|/__\|/__\|/__\|/__\|/__\|/__\|
#
- name: make-config | maildrop | Log file should be created(1)
  register: maildroplog
  ignore_errors: True
  file: >
    path=/var/log/maildrop-virtual.log
    mode=0600
    owner={{ sendmail.user.mda.username }}
    state=file

- name: make-config | maildrop | Log file should be created(2)
  when: maildroplog|failed
  file: >
    path=/var/log/maildrop-virtual.log
    mode=0600
    owner={{ sendmail.user.mda.username }}
    state=touch

- name: make-config | /root/Maildir directories should have been created
  file: >
    path=/root/Maildir/{{ item }}
    mode=0700
    state=directory
  with_items: [ "cur", "new", "tmp" ]

- name: make-config | /etc/skel/Maildir directories should have been created
  file: >
    path=/etc/skel/Maildir/{{ item }}
    mode=0700
    state=directory
  with_items: [ "cur", "new", "tmp" ]

#  ____ ____ ____ ____ ____ ____ ____ ____ 
# ||s |||e |||n |||d |||m |||a |||i |||l ||
# ||__|||__|||__|||__|||__|||__|||__|||__||
# |/__\|/__\|/__\|/__\|/__\|/__\|/__\|/__\|
#
- name: make-config | MTA Queue directories should have been created
  file: >
    path={{ sendmail.conf.mtaqueue }}/q.{{ item }}
    mode=0700
    owner=root
    group={{ sendmail.user.mta.group }}
    state=directory
  with_items: [ '0', '1', '2', '3' ]

- name: make-config | MSP Queue directories should have been created
  file: >
    path={{ sendmail.conf.msaqueue }}
    mode=0770
    owner={{ sendmail.user.msa.username }}
    group={{ sendmail.user.msa.group }}
    state=directory

- name: make-config | /var/spool/hoststat should be created
  file: >
    path=/var/spool/hoststat
    state=directory

- name: make-config | /usr/sbin/smtpd should be created
  file: >
    src=/usr/sbin/sendmail
    path=/usr/sbin/smtpd
    state=link

- name: make-config | /var/adm/sm.bin should be created
  file: >
    path=/var/adm/sm.bin
    mode=0751
    owner=root
    state=directory

- name: make-config | config distribution/backup directory should be created
  file: >
    path={{ item }}
    mode=0755
    owner=root
    state=directory
  with_items:
    - '{{ sendmail.prevconfig }}'
    - '{{ sendmail.nextconfig }}'

- name: make-config | Deploy Makefile into {{ sendmail.configroot }}/
  template: >
    src=etc/mail/Makefile.j2
    dest={{ sendmail.configroot }}/Makefile

- name: make-config | Link source code directory tree
  file: >
    src={{ sendmail.workingdir }}/sendmail-{{ sendmail.version }}/
    dest={{ sendmail.configroot }}/src
    force=yes
    owner=root
    state=link

- name: make-config | Deploy submit.mc file
  register: submitmc
  template: >
    src=etc/mail/submit.mc.j2
    dest={{ sendmail.configroot }}/src/cf/cf/submit.mc
    owner=root
    group=bin

- name: make-config | Install submit.cf into {{ sendmail.nextconfig }}
  when: submitmc.changed
  shell: >
    chdir={{ sendmail.configroot }}/src/cf/cf
    make install-submit-cf MAILDIR={{ sendmail.nextconfig }}

- name: make-config | Deploy sendmail.mc file
  register: sendmailmc
  template: >
    src=etc/mail/sendmail.mc.j2
    dest={{ sendmail.configroot }}/src/cf/cf/sendmail.mc
    owner=root
    group=bin

- name: make-config | Deploy virtmail.m4 file
  register: virtmailm4
  template: >
    src=etc/mail/virtmail.m4.j2
    dest={{ sendmail.configroot }}/src/cf/mailer/virtmail.m4

- name: make-config | Install sendmail.cf into {{ sendmail.nextconfig }}
  when: sendmailmc.changed or virtmailm4.changed
  shell: >
    chdir={{ sendmail.configroot }}/src/cf/cf
    make install-sendmail-cf MAILDIR={{ sendmail.nextconfig }}

- name: make-config | Deploy files into {{ sendmail.nextconfig }}
  template: >
    src=etc/mail/{{ item }}.j2
    dest={{ sendmail.nextconfig }}/{{ item }}
  with_items: 
    - '{{ sendmail.conf.dbmapfiles }}'
    - '{{ sendmail.conf.classfiles }}'
    - '{{ sendmail.conf.parameters }}'

- name: make-config | Initial deployment
  ignore_errors: True
  shell: >
    chdir={{ sendmail.nextconfig }}
    creates={{ sendmail.configroot }}/{{ item }}
    /bin/cp ./{{ item }} {{ sendmail.configroot }}/
  with_items: 
    - '{{ sendmail.conf.dbmapfiles }}'
    - '{{ sendmail.conf.classfiles }}'
    - '{{ sendmail.conf.parameters }}'
    - sendmail.cf
    - submit.cf

- name: make-config | Initial makemap(8)
  ignore_errors: True
  shell: >
    chdir={{ sendmail.configroot }}
    creates={{ sendmail.configroot }}/{{ item }}.db
    make {{ item }}.db
  with_items: sendmail.conf.dbmapfiles

- name: make-config | Initial backup
  when: sendmail.conf.backup == True
  ignore_errors: True
  shell: >
    chdir={{ sendmail.prevconfig }}
    creates={{ sendmail.prevconfig }}/{{ item }}
    /bin/cp ../{{ item }} ./
  with_items: 
    - '{{ sendmail.conf.dbmapfiles }}'
    - '{{ sendmail.conf.classfiles }}'
    - '{{ sendmail.conf.parameters }}'
    - sendmail.cf
    - submit.cf

- name: make-config | Backup files into {{ sendmail.prevconfig }}
  when: sendmail.conf.backup == True
  register: backupcf
  changed_when: backupcf.rc > 0
  ignore_errors: True
  shell: >
    chdir={{ sendmail.prevconfig }}
    diff -q ./{{ item }} ../{{ item }} || ( /bin/cp ../{{ item }} ./ && false )
  with_items: 
    - '{{ sendmail.conf.dbmapfiles }}'
    - '{{ sendmail.conf.classfiles }}'
    - '{{ sendmail.conf.parameters }}'
    - sendmail.cf
    - submit.cf

- name: make-config | Update submit.cf in {{ sendmail.configroot }}
  notify: Restart Sendmail
  ignore_errors: True
  register: updatesubmitcf
  changed_when: updatecf.rc > 0
  shell: >
    chdir={{ sendmail.nextconfig }}
    diff -q ../submit.cf ./submit.cf || ( /bin/cp ./submit.cf ../ && false )

- name: make-config | Update files in {{ sendmail.configroot }}
  when: sendmail.conf.update == True
  notify: Restart Sendmail
  ignore_errors: True
  register: updatecf 
  changed_when: updatecf.rc > 0
  shell: >
    chdir={{ sendmail.nextconfig }}
    diff -q ../{{ item }} ./{{ item }} || ( /bin/cp ./{{ item }} ../ && false )
  with_items: 
    - '{{ sendmail.conf.classfiles }}'
    - '{{ sendmail.conf.parameters }}'
    - sendmail.cf
    - submit.cf

- name: make-config | Update dbmaps in {{ sendmail.configroot }}
  when: sendmail.conf.update == True
  notify: Makemap DBs
  register: updatedb
  changed_when: updatedb.rc > 0
  ignore_errors: True
  shell: >
    chdir={{ sendmail.nextconfig }}
    diff -q ../{{ item }} ./{{ item }} || ( /bin/cp ./{{ item }} ../ && false )
  with_items: sendmail.conf.dbmapfiles

- name: make-config | Deploy files into {{ procmail.install }}
  template: >
    src=etc/mail/{{ item }}.j2
    dest={{ procmail.install}}/etc/{{ item }}
  with_items:
    - maildroprc
    - procmailrc

