#  _     _           _  ___    ___            _        
# | |__ (_)_ __   __| |/ _ \  / / |_ __ _ ___| | _____ 
# | '_ \| | '_ \ / _` | (_) |/ /| __/ _` / __| |/ / __|
# | |_) | | | | | (_| |\__, / / | || (_| \__ \   <\__ \
# |_.__/|_|_| |_|\__,_|  /_/_/   \__\__,_|___/_|\_\___/
#                                                      
# compile-src
- name: compile-src | REBUILD | make clean
  when: bind.rebuild == True
  command: >
    chdir={{ buildroot }}/bind-{{ bind.version }}/
    removes=Makefile
    make clean

- name: compile-src | bind {{ bind.version }} should be configured
  notify: Restart BIND
  shell: >
    chdir={{ buildroot }}/bind-{{ bind.version }}/
    creates=Makefile
    /bin/sh configure
    --prefix={{ bind.serverroot }}
    --with-openssl={{ bind.openssldir }}
    --enable-largefile
    --disable-ipv6

- name: compile-src | make bind {{ bind.version }}
  notify: Restart BIND
  register: make_bind_binary
  command: >
    chdir={{ buildroot }}/bind-{{ bind.version }}/
    creates=bin/named/named
    make

- name: compile-src | bind {{ bind.version }} should be installed
  when: make_bind_binary.changed
  notify: Restart BIND
  command: >
    chdir={{ buildroot }}/bind-{{ bind.version }}/
    make install

