#  _     _           _  ___    ___            _        
# | |__ (_)_ __   __| |/ _ \  / / |_ __ _ ___| | _____ 
# | '_ \| | '_ \ / _` | (_) |/ /| __/ _` / __| |/ / __|
# | |_) | | | | | (_| |\__, / / | || (_| \__ \   <\__ \
# |_.__/|_|_| |_|\__,_|  /_/_/   \__\__,_|___/_|\_\___/
#                                                      
- include: install-pkg.yml
  when: bind.updateonly == False
- include: create-user.yml
  when: bind.updateonly == False
- include: get-archive.yml
- include: compile-src.yml
- include: make-config.yml
  when: bind.updateonly == False
- include: boot-script.yml

- name: Start bind9
  when: bind.started == True
  service: name={{ bind.initscript }} state=started pattern=sbin/named

- name: Stop bind9
  when: bind.started == False
  service: name={{ bind.initscript }} state=stopped pattern=sbin/named

